import { createRuntimeId } from "./runtime-id.ts";

export const MESSAGE_SCHEDULE_KIND = "itemkey-message-schedule-v1";

export type ScheduleViewMode = "day" | "week" | "list";
export type ScheduleEventType = "fixed" | "flexible" | "habit" | "spontaneous";
export type SchedulePriority = "low" | "medium" | "high" | "critical";
export type ScheduleStatus = "planned" | "done" | "skipped";
export type ScheduleGoalPeriod = "day" | "week";
export type ScheduleEnergyMode = "low" | "normal" | "high";
export type ScheduleDayMode = "normal" | "shifted" | "recovery";
export type ScheduleRescheduleMode = "soft" | "normal" | "strict";
export type ScheduleWeekday = 1 | 2 | 3 | 4 | 5 | 6 | 7;
export type ScheduleRecurrenceRule =
  | {
      mode: "weekly";
      anchorDate?: string;
    }
  | {
      mode: "custom";
      anchorDate?: string;
      weekdays: ScheduleWeekday[];
    };
export type ScheduleEventEndMode = "time" | "until-morning";

export type ScheduleEvent = {
  id: string;
  taskId?: string;
  title: string;
  description?: string;
  location?: string;
  start?: string;
  end?: string;
  endDate?: string;
  durationMinutes?: number;
  approximate?: boolean;
  date?: string;
  type: ScheduleEventType;
  category?: string;
  priority?: SchedulePriority;
  status: ScheduleStatus;
  canMove?: boolean;
  canSplit?: boolean;
  deadline?: string;
  recurrence?: string;
  recurrenceRule?: ScheduleRecurrenceRule;
  recurrenceSourceId?: string;
  endMode?: ScheduleEventEndMode;
  generatedFromTaskId?: string;
  generatedFromRoutineId?: string;
  autoGenerated?: boolean;
};

export type ScheduleGoal = {
  id: string;
  title: string;
  category?: string;
  period: ScheduleGoalPeriod;
  targetCount?: number;
  targetMinutes?: number;
  currentCount?: number;
  currentMinutes?: number;
};

export type ScheduleSettings = {
  defaultDayStart?: string;
  defaultDayEnd?: string;
  bufferMinutes?: number;
  energyMode?: ScheduleEnergyMode;
  dayMode?: ScheduleDayMode;
  rescheduleMode?: ScheduleRescheduleMode;
  preserveFreeTime?: boolean;
  autoplanHorizonDays?: number;
};

export type SchedulePayload = {
  viewMode: ScheduleViewMode;
  selectedDate: string;
  events: ScheduleEvent[];
  goals: ScheduleGoal[];
  settings: ScheduleSettings;
  taskBase?: ScheduleTaskTemplate[];
  autoTasks?: ScheduleAutoTask[];
  routines?: ScheduleRoutine[];
};

export type ScheduleBlock = SchedulePayload & {
  id: string;
  title: string;
};

export type SchedulePlanningInput = {
  taskId?: string;
  text?: string;
  title?: string;
  description?: string;
  location?: string;
  durationMinutes?: number;
  date?: string;
  dateRangeStart?: string;
  dateRangeEnd?: string;
  preferredTime?: string;
  avoidedTime?: string;
  deadline?: string;
  priority?: SchedulePriority;
  category?: string;
  canMove?: boolean;
  canSplit?: boolean;
  approximate?: boolean;
  type?: ScheduleEventType;
};

export type ScheduleAutoTaskFrequency = "once" | "daily" | "some-days";

export type ScheduleAutoTask = {
  id: string;
  title: string;
  description?: string;
  category?: string;
  priority?: SchedulePriority;
  durationMinutes?: number;
  frequency?: ScheduleAutoTaskFrequency;
  date?: string;
  start?: string;
  end?: string;
  deadline?: string;
  type?: ScheduleEventType;
  canMove?: boolean;
  canSplit?: boolean;
  sourceText?: string;
  sourceRoutineId?: string;
};

export type ScheduleTaskTemplate = {
  id: string;
  title: string;
  description?: string;
  details?: string;
  checklist?: string[];
  category?: string;
  type?: ScheduleEventType;
  priority?: SchedulePriority;
  goalPeriod?: ScheduleGoalPeriod;
  goalMinutes?: number;
  goalCount?: number;
  durationMinutes?: number;
  minDurationMinutes?: number;
  maxDurationMinutes?: number;
  approximateEnd?: string;
  isSpontaneous?: boolean;
  allowAutoplan?: boolean;
  canSplit?: boolean;
  preferredTimeOfDay?: string;
  avoidedTimeOfDay?: string;
  sourceGoalId?: string;
  sourceRoutineId?: string;
  sourceAutoTaskId?: string;
};

export type ScheduleRoutine = {
  id: string;
  title: string;
  category?: string;
  priority?: SchedulePriority;
  period: ScheduleGoalPeriod;
  targetMinutes?: number;
  targetCount?: number;
  canSplit?: boolean;
  minChunkMinutes?: number;
  maxChunkMinutes?: number;
  preferredTimeOfDay?: string;
  fixedDate?: string;
  fixedStart?: string;
  fixedEnd?: string;
  sourceGoalId?: string;
  sourceAutoTaskId?: string;
};

export type ScheduleSuggestion = {
  id: string;
  date: string;
  start: string;
  end: string;
  durationMinutes: number;
  title: string;
  reason: string;
  event: ScheduleEvent;
};

export type ScheduleSpontaneousInput = {
  text?: string;
  date?: string;
  start?: string;
  end?: string;
  durationMinutes?: number;
  priority?: SchedulePriority;
  canCancel?: boolean;
  scope?: "today" | "near";
};

export type SchedulePreviewChange =
  | {
      id: string;
      kind: "add";
      event: ScheduleEvent;
      reason: string;
    }
  | {
      id: string;
      kind: "move";
      eventId: string;
      title: string;
      fromDate?: string;
      fromStart?: string;
      fromEnd?: string;
      toDate: string;
      toStart: string;
      toEnd: string;
      reason: string;
    }
  | {
      id: string;
      kind: "note";
      title: string;
      reason: string;
    };

export type ScheduleSpontaneousPreview = {
  changes: SchedulePreviewChange[];
  message: string;
  replanStartDate?: string;
  replanEndDate?: string;
};

export type ScheduleAutoplanInput = {
  text?: string;
  startDate?: string;
  horizonDays?: number;
  taskIds?: string[];
  routineIds?: string[];
};

export type ScheduleAutoplanTaskCoverage = {
  taskId: string;
  title: string;
  targetMinutes: number;
  plannedMinutes: number;
  plannedCount: number;
};

export type ScheduleAutoplanPreview = {
  changes: SchedulePreviewChange[];
  message: string;
  tasks: ScheduleAutoTask[];
  unplaced: ScheduleAutoTask[];
  startDate: string;
  endDate: string;
  taskCoverage: ScheduleAutoplanTaskCoverage[];
};

export type ScheduleSummary = {
  plannedMinutes: number;
  doneMinutes: number;
  skippedMinutes: number;
  freeMinutes: number;
  eventCount: number;
};

export type ScheduleGoalProgress = ScheduleGoal & {
  currentCount: number;
  currentMinutes: number;
};

export type ScheduleStatsBucket = {
  eventCount: number;
  totalMinutes: number;
  doneMinutes: number;
  skippedMinutes: number;
  plannedMinutes: number;
  overdueMinutes: number;
  doneCount: number;
  skippedCount: number;
  plannedCount: number;
  overdueCount: number;
  byCategory: Record<string, { count: number; minutes: number }>;
  byPriority: Record<SchedulePriority, { count: number; minutes: number }>;
};

export type ScheduleCurrentStats = {
  nowInRange: boolean;
  activeEvent: ScheduleEvent | null;
  activeRemainingMinutes: number;
  currentFreeWindow: {
    date: string;
    start: string;
    end: string;
    endDate?: string;
    durationMinutes: number;
  } | null;
  nextEvent: ScheduleEvent | null;
  nextEventStartsInMinutes: number | null;
};

export type ScheduleStats = {
  rangeStart: string;
  rangeEnd: string;
  past: ScheduleStatsBucket;
  current: ScheduleCurrentStats;
  future: ScheduleStatsBucket;
  goalProgress: ScheduleGoalProgress[];
};

type FreeWindow = {
  date: string;
  endDate?: string;
  start: number;
  end: number;
};

const DEFAULT_DAY_START = "08:00";
const DEFAULT_DAY_END = "22:00";
const DEFAULT_BUFFER_MINUTES = 15;
const DEFAULT_AUTOPLAN_HORIZON_DAYS = 7;
const MIN_EVENT_DURATION = 5;
const MAX_EVENT_DURATION = 24 * 60;
const DAY_MINUTES = 24 * 60;
const MIN_SPLIT_CHUNK_MINUTES = 25;

export function todayLocalDate(): string {
  return toLocalDateString(new Date());
}

export function toLocalDateString(date: Date): string {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, "0");
  const day = `${date.getDate()}`.padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export function addScheduleDays(date: string, days: number): string {
  const base = parseLocalDate(date) ?? parseLocalDate(todayLocalDate()) ?? new Date();
  base.setDate(base.getDate() + days);
  return toLocalDateString(base);
}

export function getScheduleWeekDates(date: string): string[] {
  const base = parseLocalDate(normalizeScheduleDate(date));
  if (!base) {
    return [];
  }

  const day = base.getDay();
  const mondayOffset = day === 0 ? -6 : 1 - day;
  base.setDate(base.getDate() + mondayOffset);

  return Array.from({ length: 7 }, (_, index) => {
    const next = new Date(base);
    next.setDate(base.getDate() + index);
    return toLocalDateString(next);
  });
}

function getScheduleWeekday(date: string): ScheduleWeekday {
  const parsed = parseLocalDate(normalizeScheduleDate(date));
  const day = parsed?.getDay() ?? 1;
  return (day === 0 ? 7 : day) as ScheduleWeekday;
}

export function getDateRange(startDate: string, endDate: string): string[] {
  const start = normalizeScheduleDate(startDate);
  const end = normalizeScheduleDate(endDate, start);
  const dates: string[] = [];
  let cursor = start;

  for (let index = 0; index < 60; index += 1) {
    dates.push(cursor);
    if (cursor >= end) {
      break;
    }
    cursor = addScheduleDays(cursor, 1);
  }

  return dates;
}

export function createDefaultSchedulePayload(
  selectedDate = todayLocalDate()
): SchedulePayload {
  return {
    viewMode: "day",
    selectedDate: normalizeScheduleDate(selectedDate),
    events: [],
    goals: [],
    settings: {
      defaultDayStart: DEFAULT_DAY_START,
      defaultDayEnd: DEFAULT_DAY_END,
      bufferMinutes: DEFAULT_BUFFER_MINUTES,
      energyMode: "normal",
      dayMode: "normal",
      rescheduleMode: "normal",
      preserveFreeTime: true,
      autoplanHorizonDays: DEFAULT_AUTOPLAN_HORIZON_DAYS,
    },
    taskBase: [],
    autoTasks: [],
    routines: [],
  };
}

export function createDefaultScheduleBlock(
  id = createScheduleId("schedule"),
  title = "Расписание",
  selectedDate = todayLocalDate()
): ScheduleBlock {
  return {
    id,
    title: normalizeScheduleTitle(title),
    ...createDefaultSchedulePayload(selectedDate),
  };
}

export function createScheduleId(prefix: string): string {
  return `${prefix}-${createRuntimeId()}`;
}

export function normalizeScheduleTitle(value: unknown): string {
  const normalized = typeof value === "string" ? value.trim() : "";
  return (normalized || "Расписание").slice(0, 90);
}

export function normalizeSchedulePayload(value: unknown): SchedulePayload {
  const raw = isObjectRecord(value) ? value : {};
  const defaults = createDefaultSchedulePayload();
  const autoTasks = normalizeScheduleAutoTasks(raw.autoTasks);
  const rawGoals = normalizeScheduleGoals(raw.goals);
  const legacyRoutines = normalizeScheduleRoutines(raw.routines);
  const taskBase = mergeScheduleTaskBase(
    normalizeScheduleTaskBase(raw.taskBase),
    rawGoals,
    autoTasks,
    legacyRoutines
  );
  const goals = mergeScheduleGoals(
    rawGoals,
    taskBase.filter(hasScheduleTaskNorm).map(scheduleTaskTemplateToGoal)
  );

  return {
    viewMode: normalizeScheduleViewMode(raw.viewMode),
    selectedDate: normalizeScheduleDate(raw.selectedDate, defaults.selectedDate),
    events: normalizeScheduleEvents(raw.events),
    goals,
    settings: normalizeScheduleSettings(raw.settings),
    taskBase,
    autoTasks,
    routines: [],
  };
}

export function normalizeScheduleBlocks(value: unknown): ScheduleBlock[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const schedules: ScheduleBlock[] = [];

  value.forEach((entry, index) => {
    if (!isObjectRecord(entry)) {
      return;
    }

    const rawId = typeof entry.id === "string" ? entry.id.trim() : "";
    const baseId = rawId || `schedule-${index + 1}`;
    let id = baseId;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());

    schedules.push({
      id,
      title: normalizeScheduleTitle(entry.title),
      ...normalizeSchedulePayload(entry),
    });
  });

  return schedules;
}

export function parseMessageScheduleContent(
  value: string | null | undefined
): SchedulePayload | null {
  const raw = typeof value === "string" ? value : "";
  const trimmed = raw.trim();
  if (!trimmed.startsWith("{")) {
    return null;
  }

  try {
    const parsed: unknown = JSON.parse(trimmed);
    if (!isObjectRecord(parsed) || parsed.kind !== MESSAGE_SCHEDULE_KIND) {
      return null;
    }

    return normalizeSchedulePayload(parsed);
  } catch {
    return null;
  }
}

export function serializeMessageScheduleContent(payload: SchedulePayload): string {
  const normalized = normalizeSchedulePayload(payload);
  return JSON.stringify({
    kind: MESSAGE_SCHEDULE_KIND,
    viewMode: normalized.viewMode,
    selectedDate: normalized.selectedDate,
    events: normalized.events,
    goals: normalized.goals,
    settings: normalized.settings,
    taskBase: normalized.taskBase ?? [],
    autoTasks: normalized.autoTasks ?? [],
  });
}

export function normalizeScheduleEvent(value: unknown, index = 0): ScheduleEvent {
  const raw = isObjectRecord(value) ? value : {};
  const type = normalizeScheduleEventType(raw.type);
  const start = normalizeOptionalTime(raw.start);
  const date = normalizeScheduleDate(raw.date);
  const endMode = normalizeScheduleEventEndMode(raw.endMode ?? raw.end);
  const rawEnd = normalizeOptionalTime(raw.end);
  const rawDuration =
    typeof raw.durationMinutes === "number" ? raw.durationMinutes : raw.duration;
  const duration = normalizeScheduleDuration(
    rawDuration,
    endMode === "until-morning" ? 60 : getDurationFromRange(start, rawEnd)
  );
  const end =
    endMode === "until-morning"
      ? undefined
      : rawEnd ?? (start ? minutesToTime(timeToMinutes(start) + duration) : undefined);
  const inferredEndDate =
    start && end && timeToMinutes(end) <= timeToMinutes(start)
      ? addScheduleDays(date, 1)
      : undefined;
  const recurrence = normalizeOptionalText(raw.recurrence, 100);
  const recurrenceRule = normalizeScheduleRecurrenceRule(
    raw.recurrenceRule,
    recurrence,
    date
  );

  return {
    id:
      typeof raw.id === "string" && raw.id.trim()
        ? raw.id.trim()
        : createScheduleId(`event-${index + 1}`),
    taskId:
      normalizeOptionalText(raw.taskId, 120) ??
      normalizeOptionalText(raw.generatedFromRoutineId, 120) ??
      normalizeOptionalText(raw.generatedFromTaskId, 120),
    title: normalizeScheduleEventTitle(raw.title),
    description: normalizeOptionalText(raw.description, 600),
    location: normalizeOptionalText(raw.location, 160),
    date,
    start,
    end,
    endDate: normalizeOptionalDate(raw.endDate) ?? inferredEndDate,
    durationMinutes: duration,
    approximate: typeof raw.approximate === "boolean" ? raw.approximate : false,
    type,
    category: normalizeOptionalText(raw.category, 80),
    priority: normalizeSchedulePriority(raw.priority),
    status: normalizeScheduleStatus(raw.status),
    canMove:
      typeof raw.canMove === "boolean"
        ? raw.canMove
        : type !== "fixed" && type !== "spontaneous",
    canSplit:
      typeof raw.canSplit === "boolean" ? raw.canSplit : type === "flexible",
    deadline: normalizeOptionalDate(raw.deadline),
    recurrence,
    recurrenceRule,
    recurrenceSourceId: normalizeOptionalText(raw.recurrenceSourceId, 120),
    endMode,
    generatedFromTaskId: normalizeOptionalText(raw.generatedFromTaskId, 120),
    generatedFromRoutineId: normalizeOptionalText(raw.generatedFromRoutineId, 120),
    autoGenerated: typeof raw.autoGenerated === "boolean" ? raw.autoGenerated : false,
  };
}

export function normalizeScheduleEvents(value: unknown): ScheduleEvent[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const events: ScheduleEvent[] = [];
  value.forEach((entry, index) => {
    const event = normalizeScheduleEvent(entry, index);
    let id = event.id;
    const baseId = id;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());
    events.push({ ...event, id });
  });
  return events;
}

export function normalizeScheduleGoal(value: unknown, index = 0): ScheduleGoal {
  const raw = isObjectRecord(value) ? value : {};
  return {
    id:
      typeof raw.id === "string" && raw.id.trim()
        ? raw.id.trim()
        : createScheduleId(`goal-${index + 1}`),
    title: normalizeScheduleEventTitle(raw.title || raw.category || "Норма"),
    category: normalizeOptionalText(raw.category, 80),
    period: raw.period === "day" ? "day" : "week",
    targetCount: normalizeOptionalPositiveInteger(raw.targetCount),
    targetMinutes: normalizeOptionalPositiveInteger(raw.targetMinutes),
    currentCount: normalizeOptionalPositiveInteger(raw.currentCount),
    currentMinutes: normalizeOptionalPositiveInteger(raw.currentMinutes),
  };
}

export function normalizeScheduleGoals(value: unknown): ScheduleGoal[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const goals: ScheduleGoal[] = [];
  value.forEach((entry, index) => {
    const goal = normalizeScheduleGoal(entry, index);
    let id = goal.id;
    const baseId = id;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());
    goals.push({ ...goal, id });
  });
  return goals;
}

export function normalizeScheduleAutoTask(
  value: unknown,
  index = 0
): ScheduleAutoTask {
  const raw = isObjectRecord(value) ? value : {};
  const start = normalizeOptionalTime(raw.start);
  const end = normalizeOptionalTime(raw.end);
  const rawDuration =
    typeof raw.durationMinutes === "number" ? raw.durationMinutes : raw.duration;

  return {
    id:
      typeof raw.id === "string" && raw.id.trim()
        ? raw.id.trim()
        : createScheduleId(`autotask-${index + 1}`),
    title: normalizeScheduleEventTitle(raw.title),
    description:
      normalizeOptionalText(raw.description, 600) ??
      normalizeOptionalText(raw.sourceText, 600),
    category: normalizeOptionalText(raw.category, 80),
    priority: normalizeSchedulePriority(raw.priority),
    durationMinutes: normalizeScheduleDuration(
      rawDuration,
      getDurationFromRange(start, end) ?? 60
    ),
    frequency: normalizeScheduleAutoTaskFrequency(raw.frequency),
    date: normalizeOptionalDate(raw.date),
    start,
    end,
    deadline: normalizeOptionalDate(raw.deadline),
    type: normalizeScheduleEventType(raw.type),
    canMove:
      typeof raw.canMove === "boolean"
        ? raw.canMove
        : normalizeScheduleEventType(raw.type) !== "fixed",
    canSplit: typeof raw.canSplit === "boolean" ? raw.canSplit : true,
    sourceText: normalizeOptionalText(raw.sourceText, 600),
    sourceRoutineId: normalizeOptionalText(raw.sourceRoutineId, 120),
  };
}

export function normalizeScheduleAutoTasks(value: unknown): ScheduleAutoTask[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const tasks: ScheduleAutoTask[] = [];
  value.forEach((entry, index) => {
    const task = normalizeScheduleAutoTask(entry, index);
    let id = task.id;
    const baseId = id;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());
    tasks.push({ ...task, id });
  });
  return tasks;
}

export function normalizeScheduleTaskTemplate(
  value: unknown,
  index = 0
): ScheduleTaskTemplate {
  const raw = isObjectRecord(value) ? value : {};
  const goalPeriod =
    raw.goalPeriod === "day" || raw.period === "day" ? "day" : "week";
  const durationMinutes = normalizeOptionalPositiveInteger(
    raw.durationMinutes ?? raw.defaultDurationMinutes
  );
  const goalMinutes = normalizeOptionalPositiveInteger(
    raw.goalMinutes ?? raw.targetMinutes
  );
  const minDurationMinutes = normalizeOptionalPositiveInteger(
    raw.minDurationMinutes ?? raw.minChunkMinutes
  );
  const maxDurationMinutes = normalizeOptionalPositiveInteger(
    raw.maxDurationMinutes ?? raw.maxChunkMinutes
  );
  const type =
    raw.isSpontaneous === true
      ? "spontaneous"
      : normalizeScheduleEventType(raw.type);

  return {
    id:
      typeof raw.id === "string" && raw.id.trim()
        ? raw.id.trim()
        : createScheduleId(`task-${index + 1}`),
    title: normalizeScheduleEventTitle(raw.title || raw.category || "Дело"),
    description: normalizeOptionalText(raw.description, 600),
    details:
      normalizeOptionalText(raw.details, 1200) ??
      normalizeOptionalText(raw.description, 1200),
    checklist: normalizeScheduleTaskChecklist(raw.checklist),
    category: normalizeOptionalText(raw.category, 80),
    type,
    priority: normalizeSchedulePriority(raw.priority),
    goalPeriod,
    goalMinutes,
    goalCount: normalizeOptionalPositiveInteger(raw.goalCount ?? raw.targetCount),
    durationMinutes:
      durationMinutes ??
      (minDurationMinutes && maxDurationMinutes
        ? Math.round((minDurationMinutes + maxDurationMinutes) / 2)
        : undefined),
    minDurationMinutes,
    maxDurationMinutes,
    approximateEnd: normalizeOptionalTime(raw.approximateEnd),
    isSpontaneous: raw.isSpontaneous === true || type === "spontaneous",
    allowAutoplan:
      typeof raw.allowAutoplan === "boolean" ? raw.allowAutoplan : true,
    canSplit: typeof raw.canSplit === "boolean" ? raw.canSplit : true,
    preferredTimeOfDay: normalizeOptionalTime(raw.preferredTimeOfDay ?? raw.start),
    avoidedTimeOfDay: normalizeOptionalTime(raw.avoidedTimeOfDay),
    sourceGoalId: normalizeOptionalText(raw.sourceGoalId, 120),
    sourceRoutineId: normalizeOptionalText(raw.sourceRoutineId, 120),
    sourceAutoTaskId: normalizeOptionalText(raw.sourceAutoTaskId, 120),
  };
}

export function normalizeScheduleTaskBase(value: unknown): ScheduleTaskTemplate[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const taskBase: ScheduleTaskTemplate[] = [];
  value.forEach((entry, index) => {
    const task = normalizeScheduleTaskTemplate(entry, index);
    let id = task.id;
    const baseId = id;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());
    taskBase.push({ ...task, id });
  });
  return taskBase;
}

export function scheduleTaskTemplateToGoal(task: ScheduleTaskTemplate): ScheduleGoal {
  return normalizeScheduleGoal({
    id: task.sourceGoalId || `goal-${task.id}`,
    title: task.title,
    category: task.id,
    period: task.goalPeriod ?? "week",
    targetCount: task.goalCount,
    targetMinutes: task.goalMinutes,
  });
}

function scheduleGoalToTaskTemplate(goal: ScheduleGoal): ScheduleTaskTemplate {
  return normalizeScheduleTaskTemplate({
    id: `task-${goal.id}`,
    title: goal.title,
    category: goal.category,
    goalPeriod: goal.period,
    goalCount: goal.targetCount,
    goalMinutes: goal.targetMinutes,
    priority: "medium",
    canSplit: true,
    allowAutoplan: true,
    sourceGoalId: goal.id,
  });
}

function scheduleAutoTaskToTaskTemplate(task: ScheduleAutoTask): ScheduleTaskTemplate {
  return normalizeScheduleTaskTemplate({
    id: task.sourceRoutineId || `task-${task.id}`,
    title: task.title,
    description: task.description,
    details: task.description,
    category: task.category,
    type: task.type,
    priority: task.priority,
    goalPeriod: task.frequency === "daily" ? "day" : "week",
    goalMinutes: task.durationMinutes,
    durationMinutes: task.durationMinutes,
    allowAutoplan: true,
    canSplit: task.canSplit,
    preferredTimeOfDay: task.start,
    sourceAutoTaskId: task.id,
  });
}

function scheduleRoutineToTaskTemplate(routine: ScheduleRoutine): ScheduleTaskTemplate {
  return normalizeScheduleTaskTemplate({
    id: routine.id,
    title: routine.title,
    category: routine.category,
    priority: routine.priority,
    goalPeriod: routine.period,
    goalMinutes: routine.targetMinutes,
    goalCount: routine.targetCount,
    minDurationMinutes: routine.minChunkMinutes,
    maxDurationMinutes: routine.maxChunkMinutes,
    preferredTimeOfDay: routine.preferredTimeOfDay ?? routine.fixedStart,
    type: routine.fixedDate || routine.fixedStart || routine.fixedEnd ? "fixed" : "flexible",
    canSplit: routine.canSplit,
    allowAutoplan: true,
    sourceGoalId: routine.sourceGoalId,
    sourceRoutineId: routine.id,
    sourceAutoTaskId: routine.sourceAutoTaskId,
  });
}

function hasScheduleTaskNorm(task: ScheduleTaskTemplate): boolean {
  return Boolean(task.goalMinutes || task.goalCount);
}

function mergeScheduleTaskBase(
  taskBase: ScheduleTaskTemplate[],
  goals: ScheduleGoal[],
  autoTasks: ScheduleAutoTask[],
  routines: ScheduleRoutine[]
): ScheduleTaskTemplate[] {
  const merged: ScheduleTaskTemplate[] = [];
  const seenIds = new Set<string>();
  const seenGoalIds = new Set<string>();
  const seenAutoTaskIds = new Set<string>();
  const seenRoutineIds = new Set<string>();

  const addTask = (task: ScheduleTaskTemplate) => {
    let id = task.id;
    const baseId = id;
    let suffix = 2;
    while (seenIds.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    const next = { ...task, id };
    seenIds.add(next.id.toLocaleLowerCase());
    if (next.sourceGoalId) {
      seenGoalIds.add(next.sourceGoalId.toLocaleLowerCase());
    }
    if (next.sourceAutoTaskId) {
      seenAutoTaskIds.add(next.sourceAutoTaskId.toLocaleLowerCase());
    }
    if (next.sourceRoutineId) {
      seenRoutineIds.add(next.sourceRoutineId.toLocaleLowerCase());
    }
    merged.push(next);
  };

  taskBase.forEach(addTask);

  routines.forEach((routine) => {
    if (
      seenRoutineIds.has(routine.id.toLocaleLowerCase()) ||
      seenIds.has(routine.id.toLocaleLowerCase())
    ) {
      return;
    }
    addTask(scheduleRoutineToTaskTemplate(routine));
  });

  goals.forEach((goal) => {
    if (seenGoalIds.has(goal.id.toLocaleLowerCase())) {
      return;
    }
    addTask(scheduleGoalToTaskTemplate(goal));
  });

  autoTasks.forEach((task) => {
    if (
      seenAutoTaskIds.has(task.id.toLocaleLowerCase()) ||
      (task.sourceRoutineId && seenIds.has(task.sourceRoutineId.toLocaleLowerCase()))
    ) {
      return;
    }
    addTask(scheduleAutoTaskToTaskTemplate(task));
  });

  return merged;
}

function normalizeScheduleTaskChecklist(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value
      .map((entry) => (typeof entry === "string" ? entry.trim() : ""))
      .filter(Boolean)
      .slice(0, 40);
  }

  if (typeof value === "string") {
    return value
      .split(/\r?\n/)
      .map((entry) => entry.replace(/^[\s*•\-–—\d.)]+/, "").trim())
      .filter(Boolean)
      .slice(0, 40);
  }

  return [];
}

export function normalizeScheduleRoutine(
  value: unknown,
  index = 0
): ScheduleRoutine {
  const raw = isObjectRecord(value) ? value : {};
  const targetMinutes = normalizeOptionalPositiveInteger(
    raw.targetMinutes ?? raw.durationMinutes
  );
  const targetCount = normalizeOptionalPositiveInteger(raw.targetCount);
  const { minChunkMinutes, maxChunkMinutes } = getDefaultRoutineChunkRange(
    targetMinutes ?? (targetCount ? targetCount * 60 : 60)
  );
  const fixedStart = normalizeOptionalTime(raw.fixedStart ?? raw.start);
  const fixedEnd = normalizeOptionalTime(raw.fixedEnd ?? raw.end);
  const fixedDate = normalizeOptionalDate(raw.fixedDate ?? raw.date);

  return {
    id:
      typeof raw.id === "string" && raw.id.trim()
        ? raw.id.trim()
        : createScheduleId(`routine-${index + 1}`),
    title: normalizeScheduleEventTitle(raw.title || raw.category || "Дело"),
    category: normalizeOptionalText(raw.category, 80),
    priority: normalizeSchedulePriority(raw.priority),
    period: raw.period === "day" ? "day" : "week",
    targetMinutes,
    targetCount,
    canSplit: typeof raw.canSplit === "boolean" ? raw.canSplit : true,
    minChunkMinutes:
      normalizeOptionalPositiveInteger(raw.minChunkMinutes) ?? minChunkMinutes,
    maxChunkMinutes:
      normalizeOptionalPositiveInteger(raw.maxChunkMinutes) ?? maxChunkMinutes,
    preferredTimeOfDay: normalizeOptionalTime(raw.preferredTimeOfDay),
    fixedDate,
    fixedStart,
    fixedEnd,
    sourceGoalId: normalizeOptionalText(raw.sourceGoalId, 120),
    sourceAutoTaskId: normalizeOptionalText(raw.sourceAutoTaskId, 120),
  };
}

export function normalizeScheduleRoutines(value: unknown): ScheduleRoutine[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<string>();
  const routines: ScheduleRoutine[] = [];
  value.forEach((entry, index) => {
    const routine = normalizeScheduleRoutine(entry, index);
    let id = routine.id;
    const baseId = id;
    let suffix = 2;
    while (seen.has(id.toLocaleLowerCase())) {
      id = `${baseId}-${suffix}`;
      suffix += 1;
    }
    seen.add(id.toLocaleLowerCase());
    routines.push({ ...routine, id });
  });
  return routines;
}

function mergeScheduleGoals(goals: ScheduleGoal[], routineGoals: ScheduleGoal[]): ScheduleGoal[] {
  const merged: ScheduleGoal[] = [];
  const seen = new Set<string>();

  [...goals, ...routineGoals].forEach((goal, index) => {
    const normalized = normalizeScheduleGoal(goal, index);
    if (seen.has(normalized.id.toLocaleLowerCase())) {
      return;
    }
    seen.add(normalized.id.toLocaleLowerCase());
    merged.push(normalized);
  });

  return merged;
}

export function normalizeScheduleSettings(value: unknown): ScheduleSettings {
  const raw = isObjectRecord(value) ? value : {};
  const bufferValue =
    typeof raw.bufferMinutes === "number" ? raw.bufferMinutes : Number(raw.bufferMinutes);
  const bufferMinutes = Number.isFinite(bufferValue)
    ? Math.min(120, Math.max(0, Math.round(bufferValue)))
    : DEFAULT_BUFFER_MINUTES;

  return {
    defaultDayStart: normalizeOptionalTime(raw.defaultDayStart) ?? DEFAULT_DAY_START,
    defaultDayEnd: normalizeOptionalTime(raw.defaultDayEnd) ?? DEFAULT_DAY_END,
    bufferMinutes,
    energyMode: normalizeScheduleEnergyMode(raw.energyMode),
    dayMode: normalizeScheduleDayMode(raw.dayMode),
    rescheduleMode: normalizeScheduleRescheduleMode(raw.rescheduleMode),
    preserveFreeTime:
      typeof raw.preserveFreeTime === "boolean" ? raw.preserveFreeTime : true,
    autoplanHorizonDays: normalizeAutoplanHorizonDays(raw.autoplanHorizonDays),
  };
}

function getRecurrenceDatesForRange(
  event: ScheduleEvent,
  startDate: string,
  endDate: string
): string[] {
  const rule = event.recurrenceRule;
  if (!rule) {
    return [];
  }

  const anchorDate = normalizeScheduleDate(rule.anchorDate || event.date, event.date);
  return getDateRange(startDate, endDate).filter((date) => {
    if (date < anchorDate) {
      return false;
    }

    if (rule.mode === "weekly") {
      return (getDateDayIndex(date) - getDateDayIndex(anchorDate)) % 7 === 0;
    }

    return rule.weekdays.includes(getScheduleWeekday(date));
  });
}

function createRecurringEventInstance(event: ScheduleEvent, date: string): ScheduleEvent {
  const sourceDate = normalizeScheduleDate(event.date);
  const dayOffset = getDateDayIndex(date) - getDateDayIndex(sourceDate);
  const endDate = event.endDate ? addScheduleDays(event.endDate, dayOffset) : undefined;
  const isSourceDate = date === sourceDate;

  return {
    ...event,
    id: isSourceDate ? event.id : `${event.id}::${date}`,
    date,
    endDate,
    recurrenceSourceId: isSourceDate ? event.recurrenceSourceId : event.id,
  };
}

function getScheduleEventsForDateRange(
  payload: SchedulePayload,
  startDate: string,
  endDate: string,
  options: { includeExplicitEventsOutsideRange?: boolean } = {}
): ScheduleEvent[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const normalizedStart = normalizeScheduleDate(startDate, normalizedPayload.selectedDate);
  const normalizedEnd = normalizeScheduleDate(endDate, normalizedStart);
  const range = {
    start: getDateDayIndex(normalizedStart) * DAY_MINUTES,
    end: (getDateDayIndex(normalizedEnd) + 1) * DAY_MINUTES,
  };
  const recurrenceStartDate = addScheduleDays(normalizedStart, -1);
  const events: ScheduleEvent[] = [];
  const seen = new Set<string>();
  const pushEvent = (event: ScheduleEvent) => {
    const key = `${event.id}:${event.date ?? ""}`;
    if (seen.has(key)) {
      return;
    }
    seen.add(key);
    events.push(event);
  };

  for (const event of normalizedPayload.events) {
    if (options.includeExplicitEventsOutsideRange && !event.recurrenceSourceId) {
      pushEvent(event);
    }

    if (event.recurrenceRule) {
      for (const date of getRecurrenceDatesForRange(
        event,
        recurrenceStartDate,
        normalizedEnd
      )) {
        const instance = createRecurringEventInstance(event, date);
        if (rangesOverlapInterval(getEventInterval(instance, normalizedPayload), range)) {
          pushEvent(instance);
        }
      }
      continue;
    }

    if (rangesOverlapInterval(getEventInterval(event, normalizedPayload), range)) {
      pushEvent(event);
    }
  }

  return events.sort((left, right) => compareScheduleEvents(left, right, normalizedPayload));
}

export function getScheduleDayEvents(
  payload: SchedulePayload,
  date = payload.selectedDate
): ScheduleEvent[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const targetDate = normalizeScheduleDate(date, normalizedPayload.selectedDate);
  const wakeInterval = getWakeIntervalForDate(normalizedPayload, targetDate);
  return getScheduleEventsForDateRange(normalizedPayload, targetDate, targetDate).filter(
    (event) => rangesOverlapInterval(getEventInterval(event, normalizedPayload), wakeInterval)
  );
}

export function getScheduleListEvents(payload: SchedulePayload): ScheduleEvent[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const horizonDays = normalizeAutoplanHorizonDays(
    normalizedPayload.settings.autoplanHorizonDays ?? DEFAULT_AUTOPLAN_HORIZON_DAYS
  );
  return getScheduleEventsForDateRange(
    normalizedPayload,
    normalizedPayload.selectedDate,
    addScheduleDays(normalizedPayload.selectedDate, Math.max(1, horizonDays) - 1),
    { includeExplicitEventsOutsideRange: true }
  );
}

export function getScheduleSummary(
  payload: SchedulePayload,
  dates: string[] = [payload.selectedDate]
): ScheduleSummary {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const normalizedDates = Array.from(
    new Set(dates.map((date) => normalizeScheduleDate(date, normalizedPayload.selectedDate)))
  );
  const wakeIntervals = normalizedDates.map((date) =>
    getWakeIntervalForDate(normalizedPayload, date)
  );
  let plannedMinutes = 0;
  let doneMinutes = 0;
  let skippedMinutes = 0;
  let eventCount = 0;

  const eventsInRange = getScheduleEventsForDateRange(
    normalizedPayload,
    normalizedDates[0] ?? normalizedPayload.selectedDate,
    normalizedDates[normalizedDates.length - 1] ?? normalizedPayload.selectedDate
  );

  for (const event of eventsInRange) {
    const eventInterval = getEventInterval(event, normalizedPayload);
    const overlapMinutes = sumIntervalOverlaps(eventInterval, wakeIntervals);
    if (overlapMinutes <= 0) {
      continue;
    }

    eventCount += 1;
    if (event.status === "done") {
      doneMinutes += overlapMinutes;
    } else if (event.status === "skipped") {
      skippedMinutes += overlapMinutes;
    } else {
      plannedMinutes += overlapMinutes;
    }
  }

  const freeMinutes = normalizedDates.reduce(
    (total, date) =>
      total +
      buildFreeWindowsForDate(normalizedPayload, date).reduce(
        (windowTotal, window) => windowTotal + Math.max(0, window.end - window.start),
        0
      ),
    0
  );

  return {
    plannedMinutes,
    doneMinutes,
    skippedMinutes,
    freeMinutes: Math.max(0, freeMinutes),
    eventCount,
  };
}

export function getScheduleFreeWindows(
  payload: SchedulePayload,
  date = payload.selectedDate
): Array<{
  date: string;
  start: string;
  end: string;
  endDate?: string;
  durationMinutes: number;
}> {
  return buildFreeWindowsForDate(payload, normalizeScheduleDate(date)).map((window) => ({
    date: window.date,
    start: minutesToTime(window.start),
    end: minutesToTime(window.end),
    endDate: window.endDate,
    durationMinutes: Math.max(0, window.end - window.start),
  }));
}

export function getScheduleGoalProgress(
  payload: SchedulePayload,
  selectedDate = payload.selectedDate
): ScheduleGoalProgress[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const weekDates = getScheduleWeekDates(selectedDate);
  const selected = normalizeScheduleDate(selectedDate);
  const progressEvents = getScheduleEventsForDateRange(
    normalizedPayload,
    weekDates[0] ?? selected,
    weekDates[weekDates.length - 1] ?? selected
  );

  return normalizedPayload.goals.map((goal) => {
    const targetDates = goal.period === "day" ? [selected] : weekDates;
    const categoryKey = normalizeGoalCategoryKey(goal);
    let currentCount = 0;
    let currentMinutes = 0;

    for (const event of progressEvents) {
      if (event.status !== "done") {
        continue;
      }

      if (!event.date || !targetDates.includes(normalizeScheduleDate(event.date))) {
        continue;
      }

      const generatedRoutineId = event.generatedFromRoutineId?.toLocaleLowerCase();
      const routineIdFromGoal = goal.id.startsWith("goal-")
        ? goal.id.slice(5).toLocaleLowerCase()
        : `routine-${goal.id}`.toLocaleLowerCase();
      const taskId = event.taskId?.toLocaleLowerCase();
      const matchesRoutine =
        (Boolean(generatedRoutineId) &&
          (generatedRoutineId === routineIdFromGoal ||
            generatedRoutineId === goal.id.toLocaleLowerCase())) ||
        (Boolean(taskId) &&
          (taskId === categoryKey ||
            taskId === routineIdFromGoal ||
            taskId === goal.id.toLocaleLowerCase()));
      if (
        !matchesRoutine &&
        categoryKey &&
        normalizeComparable(event.category || event.title) !== categoryKey
      ) {
        continue;
      }

      currentCount += 1;
      currentMinutes += getEventDurationMinutes(event, normalizedPayload);
    }

    return {
      ...goal,
      currentCount,
      currentMinutes,
    };
  });
}

export function getScheduleStats(
  payload: SchedulePayload,
  options: {
    startDate?: string;
    endDate?: string;
    now?: Date;
  } = {}
): ScheduleStats {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const rangeStart = normalizeScheduleDate(options.startDate || normalizedPayload.selectedDate);
  const rangeEnd = normalizeScheduleDate(options.endDate || rangeStart, rangeStart);
  const now = options.now ?? new Date();
  const nowDate = toLocalDateString(now);
  const nowAbs =
    getDateDayIndex(nowDate) * DAY_MINUTES + now.getHours() * 60 + now.getMinutes();
  const wakeIntervals = getDateRange(rangeStart, rangeEnd).map((date) =>
    getWakeIntervalForDate(normalizedPayload, date)
  );
  const eventsInRange = getScheduleEventsForDateRange(
    normalizedPayload,
    rangeStart,
    rangeEnd
  ).filter(
    (event) => sumIntervalOverlaps(getEventInterval(event, normalizedPayload), wakeIntervals) > 0
  );

  const past = createEmptyStatsBucket();
  const future = createEmptyStatsBucket();
  let activeEvent: ScheduleEvent | null = null;
  let activeRemainingMinutes = 0;
  let nextEvent: ScheduleEvent | null = null;
  let nextEventStartsInMinutes: number | null = null;

  for (const event of eventsInRange) {
    const interval = getEventInterval(event, normalizedPayload);
    const overlapMinutes = sumIntervalOverlaps(interval, wakeIntervals);
    if (overlapMinutes <= 0) {
      continue;
    }

    if (event.status === "planned" && interval.start <= nowAbs && interval.end > nowAbs) {
      activeEvent = event;
      activeRemainingMinutes = Math.max(0, interval.end - nowAbs);
    }

    if (interval.end <= nowAbs) {
      addEventToStatsBucket(past, event, overlapMinutes, event.status === "planned" ? "overdue" : event.status);
      continue;
    }

    if (interval.start > nowAbs && event.status === "planned") {
      const startsIn = interval.start - nowAbs;
      if (!nextEvent || startsIn < (nextEventStartsInMinutes ?? Number.POSITIVE_INFINITY)) {
        nextEvent = event;
        nextEventStartsInMinutes = startsIn;
      }
      addEventToStatsBucket(future, event, overlapMinutes, "planned");
      continue;
    }

    if (event.status === "planned" && interval.start <= nowAbs && interval.end > nowAbs) {
      addEventToStatsBucket(future, event, Math.max(0, interval.end - nowAbs), "planned");
    }
  }

  const nowInRange = wakeIntervals.some(
    (interval) => nowAbs >= interval.start && nowAbs < interval.end
  );
  const currentFreeWindow = activeEvent
    ? null
    : getCurrentFreeWindow(normalizedPayload, wakeIntervals, nowAbs);

  return {
    rangeStart,
    rangeEnd,
    past,
    current: {
      nowInRange,
      activeEvent,
      activeRemainingMinutes,
      currentFreeWindow,
      nextEvent,
      nextEventStartsInMinutes,
    },
    future,
    goalProgress: getScheduleGoalProgress(normalizedPayload, rangeStart),
  };
}

function createEmptyStatsBucket(): ScheduleStatsBucket {
  return {
    eventCount: 0,
    totalMinutes: 0,
    doneMinutes: 0,
    skippedMinutes: 0,
    plannedMinutes: 0,
    overdueMinutes: 0,
    doneCount: 0,
    skippedCount: 0,
    plannedCount: 0,
    overdueCount: 0,
    byCategory: {},
    byPriority: {
      low: { count: 0, minutes: 0 },
      medium: { count: 0, minutes: 0 },
      high: { count: 0, minutes: 0 },
      critical: { count: 0, minutes: 0 },
    },
  };
}

function addEventToStatsBucket(
  bucket: ScheduleStatsBucket,
  event: ScheduleEvent,
  minutes: number,
  status: ScheduleStatus | "overdue"
): void {
  const roundedMinutes = Math.max(0, Math.round(minutes));
  bucket.eventCount += 1;
  bucket.totalMinutes += roundedMinutes;

  if (status === "done") {
    bucket.doneCount += 1;
    bucket.doneMinutes += roundedMinutes;
  } else if (status === "skipped") {
    bucket.skippedCount += 1;
    bucket.skippedMinutes += roundedMinutes;
  } else if (status === "overdue") {
    bucket.overdueCount += 1;
    bucket.overdueMinutes += roundedMinutes;
  } else {
    bucket.plannedCount += 1;
    bucket.plannedMinutes += roundedMinutes;
  }

  const category = event.category || "Без категории";
  bucket.byCategory[category] = bucket.byCategory[category] ?? { count: 0, minutes: 0 };
  bucket.byCategory[category].count += 1;
  bucket.byCategory[category].minutes += roundedMinutes;

  const priority = event.priority ?? "medium";
  bucket.byPriority[priority].count += 1;
  bucket.byPriority[priority].minutes += roundedMinutes;
}

function getCurrentFreeWindow(
  payload: SchedulePayload,
  wakeIntervals: Array<{ start: number; end: number }>,
  nowAbs: number
): ScheduleCurrentStats["currentFreeWindow"] {
  for (const wakeInterval of wakeIntervals) {
    if (nowAbs < wakeInterval.start || nowAbs >= wakeInterval.end) {
      continue;
    }

    const date = absoluteMinuteToDateTime(wakeInterval.start).date;
    const window = buildFreeWindowsForDate(payload, date).find(
      (candidate) => nowAbs >= candidate.start && nowAbs < candidate.end
    );
    if (!window) {
      return null;
    }
    return {
      date: window.date,
      start: minutesToTime(Math.max(nowAbs, window.start)),
      end: minutesToTime(window.end),
      endDate: window.endDate,
      durationMinutes: Math.max(0, window.end - Math.max(nowAbs, window.start)),
    };
  }

  return null;
}

export function buildScheduleSuggestions(
  payload: SchedulePayload,
  input: SchedulePlanningInput,
  baseDate = payload.selectedDate
): ScheduleSuggestion[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const parsed = inferPlanningInput(input, baseDate);
  if (!parsed.title && !parsed.durationMinutes) {
    return [];
  }

  const durationMinutes = normalizeScheduleDuration(parsed.durationMinutes, 60);
  const dateRange = resolveSuggestionDateRange(normalizedPayload, parsed, baseDate);
  const preferredRange = preferredRangeForInput(parsed.preferredTime || parsed.text);
  const suggestions: ScheduleSuggestion[] = [];

  for (const date of dateRange) {
    const windows = buildFreeWindowsForDate(normalizedPayload, date);
    for (const window of windows) {
      const candidateStarts = getCandidateStarts(window, durationMinutes, preferredRange);
      for (const start of candidateStarts) {
        const end = start + durationMinutes;
        if (end > window.end) {
          continue;
        }

        const load = getScheduledMinutesForDate(normalizedPayload, date);
        const startPoint = absoluteMinuteToDateTime(start);
        const endPoint = absoluteMinuteToDateTime(end);
        const preferredBonus =
          preferredRange && rangeOverlapsPreferredRange(start, end, preferredRange)
            ? 300
            : 0;
        const deadlineBonus = parsed.deadline && date <= parsed.deadline ? 80 : 0;
        const priorityBonus =
          parsed.priority === "critical"
            ? 120
            : parsed.priority === "high"
            ? 60
            : parsed.priority === "medium"
            ? 30
            : 0;
        const score = preferredBonus + deadlineBonus + priorityBonus - load / 4 - suggestions.length;

        const event: ScheduleEvent = {
          id: createScheduleId("event"),
          taskId: parsed.taskId,
          title: parsed.title || "Новое дело",
          description: parsed.description || undefined,
          location: parsed.location,
          date: startPoint.date,
          start: startPoint.time,
          end: endPoint.time,
          endDate: endPoint.date !== startPoint.date ? endPoint.date : undefined,
          durationMinutes,
          approximate: parsed.approximate,
          type: parsed.type ?? "flexible",
          category: parsed.category || undefined,
          priority: parsed.priority ?? "medium",
          status: "planned",
          canMove: parsed.canMove ?? true,
          canSplit: parsed.canSplit ?? false,
          deadline: parsed.deadline || undefined,
        };

        suggestions.push({
          id: createScheduleId("suggestion"),
          date: event.date ?? startPoint.date,
          start: event.start ?? startPoint.time,
          end: event.end ?? endPoint.time,
          durationMinutes,
          title: event.title,
          reason: buildSuggestionReason({
            preferred: preferredBonus > 0,
            lowLoad: load < 4 * 60,
            deadline: Boolean(parsed.deadline && date <= parsed.deadline),
          }),
          event,
          score,
        } as ScheduleSuggestion & { score: number });
      }
    }
  }

  return suggestions
    .sort((left, right) => {
      const leftScore = "score" in left ? Number(left.score) : 0;
      const rightScore = "score" in right ? Number(right.score) : 0;
      if (rightScore !== leftScore) {
        return rightScore - leftScore;
      }
      if (left.date !== right.date) {
        return left.date.localeCompare(right.date);
      }
      return left.start.localeCompare(right.start);
    })
    .slice(0, 3)
    .map(({ id, date, start, end, durationMinutes, title, reason, event }) => ({
      id,
      date,
      start,
      end,
      durationMinutes,
      title,
      reason,
      event,
    }));
}

export function buildSpontaneousSchedulePreview(
  payload: SchedulePayload,
  input: ScheduleSpontaneousInput,
  baseDate = payload.selectedDate
): ScheduleSpontaneousPreview {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const inferred = inferSpontaneousInput(input, baseDate);
  const spontaneousEvent = createSpontaneousEvent(inferred);
  const changes: SchedulePreviewChange[] = [
    {
      id: createScheduleId("change"),
      kind: "add",
      event: spontaneousEvent,
      reason: "Добавить внезапное событие в расписание.",
    },
  ];

  const spontaneousInterval = getEventInterval(spontaneousEvent);
  const scopeDays = inferred.scope === "today" ? 1 : 3;
  const replanStartDate = spontaneousEvent.date ?? baseDate;
  const replanEndDate = addScheduleDays(replanStartDate, scopeDays);
  const payloadWithSpontaneous: SchedulePayload = {
    ...normalizedPayload,
    events: [...normalizedPayload.events, spontaneousEvent],
  };
  const conflictEvents = getScheduleEventsForDateRange(
    normalizedPayload,
    replanStartDate,
    replanEndDate
  );
  const hasAutoGeneratedInScope = conflictEvents.some((event) => event.autoGenerated);
  if (hasAutoGeneratedInScope) {
    changes.push({
      id: createScheduleId("change"),
      kind: "note",
      title: "Автоплан будет пересобран",
      reason: "Авто-события в ближайшем горизонте будут разложены заново вокруг спонтанного дела.",
    });
  }

  for (const event of conflictEvents) {
    if (
      event.id === spontaneousEvent.id ||
      event.autoGenerated ||
      event.status !== "planned" ||
      !rangesOverlapInterval(getEventInterval(event, normalizedPayload), spontaneousInterval)
    ) {
      continue;
    }

    if (event.recurrenceRule || event.recurrenceSourceId) {
      changes.push({
        id: createScheduleId("change"),
        kind: "note",
        title: event.title,
        reason: "Повторяющееся дело пересекается со спонтанным, но правило повтора не будет изменено автоматически.",
      });
      continue;
    }

    if (event.type === "fixed" || event.canMove === false) {
      changes.push({
        id: createScheduleId("change"),
        kind: "note",
        title: event.title,
        reason: "Фиксированное дело пересекается, но не будет перенесено автоматически.",
      });
      continue;
    }

    const suggestions = buildScheduleSuggestions(
      {
        ...payloadWithSpontaneous,
        events: payloadWithSpontaneous.events.filter((candidate) => candidate.id !== event.id),
      },
      {
        title: event.title,
        description: event.description,
        durationMinutes: getEventDurationMinutes(event, normalizedPayload),
        dateRangeStart: addScheduleDays(spontaneousEvent.date ?? baseDate, 0),
        dateRangeEnd: addScheduleDays(spontaneousEvent.date ?? baseDate, scopeDays),
        preferredTime: event.start,
        deadline: event.deadline,
        priority: event.priority,
        category: event.category,
        canMove: event.canMove,
        canSplit: event.canSplit,
        type: event.type,
      },
      spontaneousEvent.date ?? baseDate
    );

    const suggestion = suggestions[0];
    if (!suggestion) {
      changes.push({
        id: createScheduleId("change"),
        kind: "note",
        title: event.title,
        reason: "Свободное окно для переноса не найдено, лучше изменить вручную.",
      });
      continue;
    }

    changes.push({
      id: createScheduleId("change"),
      kind: "move",
      eventId: event.id,
      title: event.title,
      fromDate: event.date,
      fromStart: event.start,
      fromEnd: event.end,
      toDate: suggestion.date,
      toStart: suggestion.start,
      toEnd: suggestion.end,
      reason: suggestion.reason,
    });
  }

  return {
    changes,
    replanStartDate,
    replanEndDate,
    message:
      changes.length === 1
        ? "Будет добавлено внезапное действие. Переносов не требуется."
        : "Будет изменено:",
  };
}

export function applyScheduleSpontaneousPreview(
  payload: SchedulePayload,
  preview: ScheduleSpontaneousPreview
): SchedulePayload {
  let nextPayload = normalizeSchedulePayload(payload);

  for (const change of preview.changes) {
    if (change.kind === "add") {
      nextPayload = {
        ...nextPayload,
        events: normalizeScheduleEvents([...nextPayload.events, change.event]),
      };
      continue;
    }

    if (change.kind === "move") {
      nextPayload = {
        ...nextPayload,
        events: normalizeScheduleEvents(
          nextPayload.events.map((event) =>
            event.id === change.eventId
              ? {
                  ...event,
                  date: change.toDate,
                  start: change.toStart,
                  end: change.toEnd,
                  endDate:
                    timeToMinutes(change.toEnd) <= timeToMinutes(change.toStart)
                      ? addScheduleDays(change.toDate, 1)
                      : undefined,
                  durationMinutes: getDurationFromRange(change.toStart, change.toEnd),
                }
              : event
          )
        ),
      };
    }
  }

  const replanStartDate =
    preview.replanStartDate ??
    preview.changes.find(
      (change): change is Extract<SchedulePreviewChange, { kind: "add" }> =>
        change.kind === "add"
    )?.event.date;
  const replanEndDate = preview.replanEndDate ?? replanStartDate;
  const shouldReplanAutoEvents =
    Boolean(nextPayload.autoTasks?.length) ||
    (replanStartDate && replanEndDate
      ? nextPayload.events.some((event) =>
          isAutoGeneratedEventInDateRange(event, replanStartDate, replanEndDate)
        )
      : false);

  if (replanStartDate && replanEndDate && shouldReplanAutoEvents) {
    const horizonDays = Math.max(
      1,
      getDateDayIndex(replanEndDate) - getDateDayIndex(replanStartDate) + 1
    );
    nextPayload = applyScheduleAutoplanPreview(
      nextPayload,
      buildScheduleAutoplanPreview(
        nextPayload,
        { startDate: replanStartDate, horizonDays },
        replanStartDate
      )
    );
  }

  return nextPayload;
}

export function buildScheduleAutoplanPreview(
  payload: SchedulePayload,
  input: ScheduleAutoplanInput,
  baseDate = payload.selectedDate
): ScheduleAutoplanPreview {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const settings = normalizeScheduleSettings(normalizedPayload.settings);
  const startDate = normalizeScheduleDate(input.startDate || baseDate, normalizedPayload.selectedDate);
  const horizonDays = normalizeAutoplanHorizonDays(
    input.horizonDays ?? settings.autoplanHorizonDays ?? DEFAULT_AUTOPLAN_HORIZON_DAYS
  );
  const endDate = addScheduleDays(startDate, horizonDays - 1);
  const hasExplicitTaskSelection =
    Array.isArray(input.taskIds) || Array.isArray(input.routineIds);
  const selectedTaskIds = new Set(
    (input.taskIds ?? input.routineIds ?? []).map((id) => id.trim()).filter(Boolean)
  );
  const selectedTasks =
    hasExplicitTaskSelection
      ? normalizedPayload.taskBase?.filter(
          (task) => selectedTaskIds.has(task.id) && task.allowAutoplan !== false
        ) ?? []
      : [];
  const templateTasks = selectedTasks.flatMap((task) =>
    createAutoTasksFromTemplate(task, startDate, horizonDays)
  );
  const parsedTasks = parseAutoplanTasksFromText(input.text ?? "", startDate);
  const tasks =
    templateTasks.length > 0 || parsedTasks.length > 0
      ? normalizeScheduleAutoTasks([...templateTasks, ...parsedTasks])
      : hasExplicitTaskSelection
      ? []
      : normalizeScheduleAutoTasks(normalizedPayload.autoTasks);
  const changes: SchedulePreviewChange[] = [];
  const unplaced: ScheduleAutoTask[] = [];

  let workingPayload: SchedulePayload = {
    ...normalizedPayload,
    events: normalizedPayload.events.filter(
      (event) => !isAutoGeneratedEventInDateRange(event, startDate, endDate)
    ),
    taskBase: normalizedPayload.taskBase ?? [],
    autoTasks: tasks,
    routines: [],
  };

  const removedCount = normalizedPayload.events.length - workingPayload.events.length;
  if (removedCount > 0) {
    changes.push({
      id: createScheduleId("change"),
      kind: "note",
      title: "Автоплан будет пересобран",
      reason: `Старые авто-события в горизонте будут заменены: ${removedCount}.`,
    });
  }

  const instances = expandAutoTaskInstances(tasks, startDate, horizonDays);
  const fixedInstances = instances.filter((instance) => instance.task.type === "fixed");
  const flexibleInstances = instances
    .filter((instance) => instance.task.type !== "fixed")
    .sort(compareAutoTaskInstances);

  for (const instance of fixedInstances) {
    const event = createEventFromAutoTask(instance.task, instance.date, {
      type: "fixed",
      canMove: false,
    });
    changes.push({
      id: createScheduleId("change"),
      kind: "add",
      event,
      reason: "Фиксированное дело из автоплана.",
    });
    workingPayload = {
      ...workingPayload,
      events: normalizeScheduleEvents([...workingPayload.events, event]),
    };
  }

  for (const instance of flexibleInstances) {
    const placedEvents = placeAutoTaskInstance(workingPayload, instance.task, instance.date, endDate);
    if (placedEvents.length === 0) {
      unplaced.push(instance.task);
      changes.push({
        id: createScheduleId("change"),
        kind: "note",
        title: instance.task.title,
        reason: "Не нашлось свободного окна в выбранном горизонте.",
      });
      continue;
    }

    for (const event of placedEvents) {
      changes.push({
        id: createScheduleId("change"),
        kind: "add",
        event,
        reason:
          placedEvents.length > 1
            ? "Делимое дело поставлено частью."
            : "Гибкое дело поставлено в свободное окно.",
      });
    }
    workingPayload = {
      ...workingPayload,
      events: normalizeScheduleEvents([...workingPayload.events, ...placedEvents]),
    };
  }

  return {
    changes,
    message:
      changes.length > 0
        ? "Автораспределение готово к применению."
        : "Не найдено задач для автораспределения.",
    tasks,
    unplaced,
    startDate,
    endDate,
    taskCoverage: buildTaskCoverage(selectedTasks, changes, horizonDays),
  };
}

export function applyScheduleAutoplanPreview(
  payload: SchedulePayload,
  preview: ScheduleAutoplanPreview
): SchedulePayload {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const preservedEvents = normalizedPayload.events.filter(
    (event) => !isAutoGeneratedEventInDateRange(event, preview.startDate, preview.endDate)
  );
  const addedEvents = preview.changes
    .filter((change): change is Extract<SchedulePreviewChange, { kind: "add" }> => change.kind === "add")
    .map((change) => change.event);

  return normalizeSchedulePayload({
    ...normalizedPayload,
    viewMode: "week",
    selectedDate: preview.startDate,
    events: normalizeScheduleEvents([...preservedEvents, ...addedEvents]),
    autoTasks: normalizeScheduleAutoTasks(preview.tasks),
    taskBase: normalizedPayload.taskBase ?? [],
    routines: [],
  });
}

export function formatScheduleMinutes(minutes: number): string {
  const normalized = Math.max(0, Math.round(minutes));
  const hours = Math.floor(normalized / 60);
  const rest = normalized % 60;
  if (hours === 0) {
    return `${rest}м`;
  }
  if (rest === 0) {
    return `${hours}ч`;
  }
  return `${hours}ч ${rest}м`;
}

export function formatScheduleDateShort(date: string): string {
  const parsed = parseLocalDate(date);
  if (!parsed) {
    return date;
  }

  return new Intl.DateTimeFormat("ru-RU", {
    day: "2-digit",
    month: "2-digit",
    weekday: "short",
  }).format(parsed);
}

export function formatScheduleTimeRange(
  event: ScheduleEvent,
  payload?: SchedulePayload
): string {
  if (event.endMode === "until-morning" && event.start) {
    return `${event.start}-до утра`;
  }
  if (event.start && event.end) {
    return `${event.start}-${event.end}`;
  }
  if (event.start) {
    return `${event.start} · ${formatScheduleMinutes(getEventDurationMinutes(event, payload))}`;
  }
  return formatScheduleMinutes(getEventDurationMinutes(event, payload));
}

export function getEventDurationMinutes(
  event: ScheduleEvent,
  payload?: SchedulePayload
): number {
  if (event.endMode === "until-morning") {
    const interval = getEventInterval(event, payload);
    return Math.max(MIN_EVENT_DURATION, interval.end - interval.start);
  }
  return normalizeScheduleDuration(
    event.durationMinutes,
    getDurationFromRange(event.start, event.end) ?? 60
  );
}

export function timeToMinutes(time: string): number {
  const normalized = normalizeOptionalTime(time) ?? time;
  const [hours, minutes] = normalized.split(":").map((part) => Number(part));
  if (!Number.isFinite(hours) || !Number.isFinite(minutes)) {
    return 0;
  }
  return Math.min(DAY_MINUTES, Math.max(0, hours * 60 + minutes));
}

export function minutesToTime(minutes: number): string {
  const rounded = Math.round(minutes);
  const wrapped = ((rounded % DAY_MINUTES) + DAY_MINUTES) % DAY_MINUTES;
  const hours = Math.floor(wrapped / 60);
  const rest = wrapped % 60;
  return `${`${hours}`.padStart(2, "0")}:${`${rest}`.padStart(2, "0")}`;
}

export function normalizeScheduleTimeInput(value: unknown): string | undefined {
  return normalizeOptionalTime(value);
}

function isObjectRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function normalizeScheduleViewMode(value: unknown): ScheduleViewMode {
  return value === "week" || value === "list" ? value : "day";
}

function normalizeScheduleEventType(value: unknown): ScheduleEventType {
  return value === "fixed" ||
    value === "habit" ||
    value === "spontaneous" ||
    value === "flexible"
    ? value
    : "flexible";
}

function normalizeSchedulePriority(value: unknown): SchedulePriority {
  return value === "low" || value === "high" || value === "critical"
    ? value
    : "medium";
}

function normalizeScheduleStatus(value: unknown): ScheduleStatus {
  return value === "done" || value === "skipped" ? value : "planned";
}

function normalizeScheduleEnergyMode(value: unknown): ScheduleEnergyMode {
  return value === "low" || value === "high" ? value : "normal";
}

function normalizeScheduleDayMode(value: unknown): ScheduleDayMode {
  return value === "shifted" || value === "recovery" ? value : "normal";
}

function normalizeScheduleRescheduleMode(value: unknown): ScheduleRescheduleMode {
  return value === "soft" || value === "strict" ? value : "normal";
}

function normalizeScheduleEventEndMode(value: unknown): ScheduleEventEndMode {
  if (typeof value !== "string") {
    return "time";
  }
  const normalized = value.trim().toLocaleLowerCase();
  return normalized === "until-morning" || normalized === "до утра"
    ? "until-morning"
    : "time";
}

function normalizeScheduleAutoTaskFrequency(value: unknown): ScheduleAutoTaskFrequency {
  return value === "daily" || value === "some-days" ? value : "once";
}

function normalizeScheduleWeekday(value: unknown): ScheduleWeekday | null {
  const numeric = typeof value === "number" ? value : Number(value);
  if (
    numeric === 1 ||
    numeric === 2 ||
    numeric === 3 ||
    numeric === 4 ||
    numeric === 5 ||
    numeric === 6 ||
    numeric === 7
  ) {
    return numeric;
  }
  return null;
}

function normalizeScheduleWeekdays(value: unknown): ScheduleWeekday[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const seen = new Set<ScheduleWeekday>();
  for (const entry of value) {
    const weekday = normalizeScheduleWeekday(entry);
    if (weekday) {
      seen.add(weekday);
    }
  }
  return Array.from(seen).sort((left, right) => left - right);
}

function normalizeScheduleRecurrenceRule(
  value: unknown,
  legacyRecurrence: string | undefined,
  eventDate: string
): ScheduleRecurrenceRule | undefined {
  const anchorDate = normalizeScheduleDate(
    isObjectRecord(value) ? value.anchorDate : undefined,
    eventDate
  );

  if (isObjectRecord(value)) {
    if (value.mode === "weekly") {
      return { mode: "weekly", anchorDate };
    }

    if (value.mode === "custom") {
      const weekdays = normalizeScheduleWeekdays(value.weekdays);
      if (weekdays.length > 0) {
        return { mode: "custom", anchorDate, weekdays };
      }
    }
  }

  const normalizedLegacy = legacyRecurrence?.toLocaleLowerCase() ?? "";
  if (
    normalizedLegacy.includes("каждую неделю") ||
    normalizedLegacy.includes("еженед") ||
    normalizedLegacy.includes("weekly")
  ) {
    return { mode: "weekly", anchorDate };
  }

  return undefined;
}

function normalizeAutoplanHorizonDays(value: unknown): number {
  const numericValue = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(numericValue)) {
    return DEFAULT_AUTOPLAN_HORIZON_DAYS;
  }
  return Math.min(30, Math.max(1, Math.round(numericValue)));
}

function normalizeScheduleDate(value: unknown, fallback = todayLocalDate()): string {
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }
  return fallback;
}

function normalizeOptionalDate(value: unknown): string | undefined {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)
    ? value
    : undefined;
}

function normalizeOptionalTime(value: unknown): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const trimmed = value.trim().toLocaleLowerCase();
  const match = trimmed.match(/^([01]?\d|2[0-3]):([0-5]\d)$/);
  if (!match) {
    const meridiemMatch = trimmed.match(/^(\d{1,2})(?::([0-5]\d))?\s*([ap])\.?\s*m\.?$/i);
    if (!meridiemMatch) {
      return undefined;
    }

    let hours = Number(meridiemMatch[1]);
    const minutes = Number(meridiemMatch[2] ?? 0);
    const meridiem = meridiemMatch[3].toLocaleLowerCase();
    if (!Number.isFinite(hours) || hours < 1 || hours > 12) {
      return undefined;
    }
    if (meridiem === "p" && hours !== 12) {
      hours += 12;
    }
    if (meridiem === "a" && hours === 12) {
      hours = 0;
    }
    return `${`${hours}`.padStart(2, "0")}:${`${minutes}`.padStart(2, "0")}`;
  }

  return `${match[1].padStart(2, "0")}:${match[2]}`;
}

function normalizeScheduleDuration(value: unknown, fallback = 60): number {
  const numericValue = typeof value === "number" ? value : Number(value);
  const minutes = Number.isFinite(numericValue) ? numericValue : fallback;
  return Math.min(MAX_EVENT_DURATION, Math.max(MIN_EVENT_DURATION, Math.round(minutes)));
}

function normalizeScheduleEventTitle(value: unknown): string {
  const normalized = typeof value === "string" ? value.trim() : "";
  return (normalized || "Дело").slice(0, 120);
}

function normalizeOptionalText(value: unknown, maxLength: number): string | undefined {
  const normalized = typeof value === "string" ? value.trim() : "";
  return normalized ? normalized.slice(0, maxLength) : undefined;
}

function normalizeOptionalPositiveInteger(value: unknown): number | undefined {
  const numericValue = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(numericValue) || numericValue <= 0) {
    return undefined;
  }
  return Math.round(numericValue);
}

function parseLocalDate(value: string): Date | null {
  const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) {
    return null;
  }

  const date = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  return Number.isNaN(date.getTime()) ? null : date;
}

function getDurationFromRange(start: unknown, end: unknown): number | undefined {
  const normalizedStart = normalizeOptionalTime(start);
  const normalizedEnd = normalizeOptionalTime(end);
  if (!normalizedStart || !normalizedEnd) {
    return undefined;
  }

  const startMinutes = timeToMinutes(normalizedStart);
  let endMinutes = timeToMinutes(normalizedEnd);
  if (endMinutes <= startMinutes) {
    endMinutes += DAY_MINUTES;
  }
  const duration = endMinutes - startMinutes;
  return duration > 0 ? duration : undefined;
}

function compareScheduleEvents(
  left: ScheduleEvent,
  right: ScheduleEvent,
  payload?: SchedulePayload
): number {
  const leftInterval = getEventInterval(left, payload);
  const rightInterval = getEventInterval(right, payload);
  if (leftInterval.start !== rightInterval.start) {
    return leftInterval.start - rightInterval.start;
  }
  return left.title.localeCompare(right.title, "ru-RU");
}

function getDateDayIndex(date: string): number {
  const match = date.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) {
    return getDateDayIndex(todayLocalDate());
  }
  return Math.floor(
    Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])) / 86400000
  );
}

function dayIndexToDate(dayIndex: number): string {
  const date = new Date(dayIndex * 86400000);
  const year = date.getUTCFullYear();
  const month = `${date.getUTCMonth() + 1}`.padStart(2, "0");
  const day = `${date.getUTCDate()}`.padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function dateTimeToAbsoluteMinute(date: string, time: string): number {
  return getDateDayIndex(normalizeScheduleDate(date)) * DAY_MINUTES + timeToMinutes(time);
}

function absoluteMinuteToDateTime(minutes: number): { date: string; time: string } {
  const rounded = Math.round(minutes);
  const dayIndex = Math.floor(rounded / DAY_MINUTES);
  return {
    date: dayIndexToDate(dayIndex),
    time: minutesToTime(rounded),
  };
}

function getWakeIntervalForDate(
  payload: SchedulePayload,
  date: string
): { start: number; end: number } {
  const settings = normalizeScheduleSettings(payload.settings);
  let dayStart = timeToMinutes(settings.defaultDayStart ?? DEFAULT_DAY_START);
  let dayEnd = timeToMinutes(settings.defaultDayEnd ?? DEFAULT_DAY_END);

  if (settings.energyMode === "low" || settings.dayMode === "recovery") {
    dayStart += 60;
    dayEnd -= 30;
  }
  if (settings.dayMode === "shifted") {
    dayStart += 90;
    dayEnd += 60;
  }

  dayStart = Math.max(0, dayStart);
  while (dayEnd <= dayStart) {
    dayEnd += DAY_MINUTES;
  }

  const base = getDateDayIndex(normalizeScheduleDate(date, payload.selectedDate)) * DAY_MINUTES;
  return {
    start: base + dayStart,
    end: base + dayEnd,
  };
}

function getEventInterval(
  event: ScheduleEvent,
  payload?: SchedulePayload
): { start: number; end: number } {
  const date = normalizeScheduleDate(event.date);
  const start = event.start ?? DEFAULT_DAY_START;
  const startAbs = dateTimeToAbsoluteMinute(date, start);

  if (event.endMode === "until-morning") {
    const nextDate = addScheduleDays(date, 1);
    const endAbs = payload
      ? getWakeIntervalForDate(payload, nextDate).start
      : dateTimeToAbsoluteMinute(nextDate, DEFAULT_DAY_START);
    return {
      start: startAbs,
      end: Math.max(startAbs + MIN_EVENT_DURATION, endAbs),
    };
  }

  if (event.end) {
    const endDate =
      event.endDate ??
      (timeToMinutes(event.end) <= timeToMinutes(start) ? addScheduleDays(date, 1) : date);
    let endAbs = dateTimeToAbsoluteMinute(endDate, event.end);
    if (endAbs <= startAbs) {
      endAbs = startAbs + getEventDurationMinutes(event);
    }
    return { start: startAbs, end: endAbs };
  }

  return { start: startAbs, end: startAbs + getEventDurationMinutes(event) };
}

function rangesOverlapInterval(
  left: { start: number; end: number },
  right: { start: number; end: number }
): boolean {
  return rangesOverlap(left.start, left.end, right.start, right.end);
}

function sumIntervalOverlaps(
  interval: { start: number; end: number },
  ranges: Array<{ start: number; end: number }>
): number {
  return ranges.reduce((total, range) => {
    const start = Math.max(interval.start, range.start);
    const end = Math.min(interval.end, range.end);
    return total + Math.max(0, end - start);
  }, 0);
}

function freeWindowFromAbsoluteRange(start: number, end: number): FreeWindow {
  const startPoint = absoluteMinuteToDateTime(start);
  const endPoint = absoluteMinuteToDateTime(end);
  return {
    date: startPoint.date,
    endDate: endPoint.date !== startPoint.date ? endPoint.date : undefined,
    start,
    end,
  };
}

function buildFreeWindowsForDate(payload: SchedulePayload, date: string): FreeWindow[] {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const dayInterval = getWakeIntervalForDate(normalizedPayload, date);
  const settings = normalizeScheduleSettings(normalizedPayload.settings);
  const buffer = settings.preserveFreeTime ? settings.bufferMinutes ?? DEFAULT_BUFFER_MINUTES : 0;
  const busy = getScheduleEventsForDateRange(normalizedPayload, date, date)
    .filter((event) => {
      if (event.status === "skipped") {
        return false;
      }
      return rangesOverlapInterval(getEventInterval(event, normalizedPayload), dayInterval);
    })
    .map((event) => {
      const interval = getEventInterval(event, normalizedPayload);
      const eventBuffer =
        event.type === "fixed" || event.type === "spontaneous" ? 0 : buffer;
      return {
        start: Math.max(dayInterval.start, interval.start - eventBuffer),
        end: Math.min(dayInterval.end, interval.end + eventBuffer),
      };
    })
    .filter((range) => range.end > range.start)
    .sort((left, right) => left.start - right.start);

  const windows: FreeWindow[] = [];
  let cursor = dayInterval.start;
  for (const range of busy) {
    if (range.start > cursor) {
      windows.push(freeWindowFromAbsoluteRange(cursor, range.start));
    }
    cursor = Math.max(cursor, range.end);
  }

  if (cursor < dayInterval.end) {
    windows.push(freeWindowFromAbsoluteRange(cursor, dayInterval.end));
  }

  return windows.filter((window) => window.end - window.start >= MIN_EVENT_DURATION);
}

function inferPlanningInput(
  input: SchedulePlanningInput,
  baseDate: string
): Required<Pick<SchedulePlanningInput, "text">> & SchedulePlanningInput {
  const text = input.text?.trim() ?? "";
  const durationMinutes =
    input.durationMinutes && input.durationMinutes > 0
      ? input.durationMinutes
      : parseDurationFromText(text);
  return {
    ...input,
    text,
    title: normalizeAssistantTitle(input.title || text),
    durationMinutes,
    date: input.date || inferDateFromText(text, baseDate),
    deadline: input.deadline || inferDeadlineFromText(text, baseDate),
    preferredTime: input.preferredTime || inferPreferredTimeFromText(text),
    priority: input.priority ?? inferPriorityFromText(text),
    type: input.type ?? (text.toLocaleLowerCase().includes("привыч") ? "habit" : "flexible"),
  };
}

function inferSpontaneousInput(
  input: ScheduleSpontaneousInput,
  baseDate: string
): ScheduleSpontaneousInput & {
  title: string;
  date: string;
  start: string;
  durationMinutes: number;
  priority: SchedulePriority;
  scope: "today" | "near";
} {
  const text = input.text?.trim() ?? "";
  const inferredRange = parseTimeRangeFromText(text);
  const start =
    normalizeOptionalTime(input.start) ??
    inferredRange?.start ??
    normalizeOptionalTime(inferPreferredTimeFromText(text)) ??
    "18:00";
  const durationMinutes = normalizeScheduleDuration(
    input.durationMinutes,
    input.end
      ? getDurationFromRange(start, input.end)
      : inferredRange
      ? getDurationFromRange(inferredRange.start, inferredRange.end)
      : parseDurationFromText(text) || 60
  );

  return {
    ...input,
    title: normalizeAssistantTitle(text || "Спонтанное действие"),
    date: input.date || inferDateFromText(text, baseDate) || baseDate,
    start,
    durationMinutes,
    priority: input.priority ?? "high",
    scope: input.scope ?? "near",
  };
}

function createSpontaneousEvent(
  input: ReturnType<typeof inferSpontaneousInput>
): ScheduleEvent {
  const startMinutes = timeToMinutes(input.start);
  const startAbs = dateTimeToAbsoluteMinute(input.date, input.start);
  const endPoint = absoluteMinuteToDateTime(startAbs + input.durationMinutes);
  return {
    id: createScheduleId("event"),
    title: input.title || "Спонтанное действие",
    description: input.text || undefined,
    date: input.date,
    start: input.start,
    end: minutesToTime(startMinutes + input.durationMinutes),
    endDate: endPoint.date !== input.date ? endPoint.date : undefined,
    durationMinutes: input.durationMinutes,
    type: "spontaneous",
    priority: input.priority,
    status: "planned",
    canMove: Boolean(input.canCancel),
    canSplit: false,
  };
}

function resolveSuggestionDateRange(
  payload: SchedulePayload,
  input: SchedulePlanningInput,
  baseDate: string
): string[] {
  const startDate = normalizeScheduleDate(
    input.dateRangeStart || input.date || baseDate,
    payload.selectedDate
  );
  const endDate = normalizeScheduleDate(
    input.dateRangeEnd || input.deadline || addScheduleDays(startDate, 6),
    startDate
  );

  const dates: string[] = [];
  let cursor = startDate;
  for (let index = 0; index < 14; index += 1) {
    dates.push(cursor);
    if (cursor >= endDate) {
      break;
    }
    cursor = addScheduleDays(cursor, 1);
  }

  return dates;
}

function getCandidateStarts(
  window: FreeWindow,
  durationMinutes: number,
  preferredRange: { start: number; end: number } | null
): number[] {
  const starts = new Set<number>();
  const roundedStart = Math.ceil(window.start / 15) * 15;
  starts.add(roundedStart);

  if (preferredRange) {
    const preferredBase = Math.floor(window.start / DAY_MINUTES) * DAY_MINUTES;
    let preferredStart = preferredBase + preferredRange.start;
    let preferredEnd = preferredBase + preferredRange.end;
    if (preferredEnd <= preferredStart) {
      preferredEnd += DAY_MINUTES;
    }
    if (preferredEnd < window.start) {
      preferredStart += DAY_MINUTES;
      preferredEnd += DAY_MINUTES;
    }
    starts.add(Math.max(roundedStart, Math.ceil(preferredStart / 15) * 15));
    starts.add(
      Math.max(
        roundedStart,
        Math.ceil((preferredEnd - durationMinutes) / 15) * 15
      )
    );
  }

  return Array.from(starts)
    .filter((start) => start >= window.start && start + durationMinutes <= window.end)
    .sort((left, right) => left - right);
}

function rangeOverlapsPreferredRange(
  start: number,
  end: number,
  preferredRange: { start: number; end: number }
): boolean {
  const base = Math.floor(start / DAY_MINUTES) * DAY_MINUTES;
  const ranges = [base, base + DAY_MINUTES, base - DAY_MINUTES].map((rangeBase) => {
    const preferredStart = rangeBase + preferredRange.start;
    let preferredEnd = rangeBase + preferredRange.end;
    if (preferredEnd <= preferredStart) {
      preferredEnd += DAY_MINUTES;
    }
    return { start: preferredStart, end: preferredEnd };
  });
  return ranges.some((range) => rangesOverlap(start, end, range.start, range.end));
}

function preferredRangeForInput(value: string | undefined): { start: number; end: number } | null {
  if (!value) {
    return null;
  }

  const time = normalizeOptionalTime(value);
  if (time) {
    const minutes = timeToMinutes(time);
    return { start: Math.max(0, minutes - 90), end: Math.min(24 * 60, minutes + 150) };
  }

  const lower = value.toLocaleLowerCase();
  if (lower.includes("утр") || lower.includes("morning")) {
    return { start: timeToMinutes("08:00"), end: timeToMinutes("12:00") };
  }
  if (lower.includes("дн") || lower.includes("day")) {
    return { start: timeToMinutes("12:00"), end: timeToMinutes("17:00") };
  }
  if (lower.includes("веч") || lower.includes("evening")) {
    return { start: timeToMinutes("17:00"), end: timeToMinutes("22:00") };
  }

  return null;
}

function getScheduledMinutesForDate(payload: SchedulePayload, date: string): number {
  const normalizedPayload = normalizeSchedulePayload(payload);
  const wakeInterval = getWakeIntervalForDate(normalizedPayload, date);
  return getScheduleEventsForDateRange(normalizedPayload, date, date).reduce((total, event) => {
    if (event.status === "skipped") {
      return total;
    }
    return total + sumIntervalOverlaps(getEventInterval(event, normalizedPayload), [wakeInterval]);
  }, 0);
}

function rangesOverlap(
  leftStart: number,
  leftEnd: number,
  rightStart: number,
  rightEnd: number
): boolean {
  return leftStart < rightEnd && rightStart < leftEnd;
}

function parseDurationFromText(text: string): number | undefined {
  const lower = text.toLocaleLowerCase();
  const hourMatch = lower.match(
    /(\d+(?:[,.]\d+)?)\s*(?:часов|часа|час|ч|hours?|h)(?=$|\s|[.,;:!?])/
  );
  if (hourMatch) {
    return Math.round(Number(hourMatch[1].replace(",", ".")) * 60);
  }

  const minuteMatch = lower.match(
    /(\d+)\s*(?:минут|минуты|мин|м|minutes?|m)(?=$|\s|[.,;:!?])/
  );
  if (minuteMatch) {
    return Number(minuteMatch[1]);
  }

  return undefined;
}

function parseTimeRangeFromText(text: string): { start: string; end: string } | null {
  const timePattern = String.raw`(\d{1,2})(?::([0-5]\d))?\s*([ap]\.?\s*m\.?)?`;
  const match = text.match(
    new RegExp(`${timePattern}\\s*(?:-|до|по|to|—|–)\\s*${timePattern}`, "i")
  );
  if (!match) {
    return null;
  }

  const start = normalizeOptionalTime(`${match[1]}:${match[2] ?? "00"}${match[3] ?? ""}`);
  const end = normalizeOptionalTime(`${match[4]}:${match[5] ?? "00"}${match[6] ?? ""}`);
  return start && end ? { start, end } : null;
}

function inferPreferredTimeFromText(text: string): string | undefined {
  const range = parseTimeRangeFromText(text);
  if (range) {
    return range.start;
  }

  const timeMatch = text.match(
    /(\d{1,2}):([0-5]\d)\s*([ap]\.?\s*m\.?)?|(\d{1,2})\s*([ap]\.?\s*m\.?)/i
  );
  if (timeMatch) {
    return normalizeOptionalTime(
      timeMatch[1]
        ? `${timeMatch[1]}:${timeMatch[2] ?? "00"}${timeMatch[3] ?? ""}`
        : `${timeMatch[4]}:00${timeMatch[5] ?? ""}`
    );
  }

  const lower = text.toLocaleLowerCase();
  if (lower.includes("утр")) {
    return "09:00";
  }
  if (lower.includes("дн") || lower.includes("после обеда")) {
    return "14:00";
  }
  if (lower.includes("веч")) {
    return "18:00";
  }

  return undefined;
}

function inferDateFromText(text: string, baseDate: string): string | undefined {
  const lower = text.toLocaleLowerCase();
  if (lower.includes("сегодня")) {
    return baseDate;
  }
  if (lower.includes("завтра")) {
    return addScheduleDays(baseDate, 1);
  }
  if (lower.includes("послезавтра")) {
    return addScheduleDays(baseDate, 2);
  }

  const weekdays = [
    ["воскрес", 0],
    ["понедель", 1],
    ["вторник", 2],
    ["сред", 3],
    ["четвер", 4],
    ["пятниц", 5],
    ["суббот", 6],
  ] as const;
  const base = parseLocalDate(baseDate);
  if (!base) {
    return undefined;
  }

  for (const [fragment, targetDay] of weekdays) {
    if (!lower.includes(fragment)) {
      continue;
    }
    const currentDay = base.getDay();
    const offset = (targetDay - currentDay + 7) % 7;
    return addScheduleDays(baseDate, offset);
  }

  return undefined;
}

function inferDeadlineFromText(text: string, baseDate: string): string | undefined {
  const lower = text.toLocaleLowerCase();
  if (!lower.includes("дедлайн") && !lower.includes("до ")) {
    return undefined;
  }
  return inferDateFromText(text, baseDate);
}

function inferPriorityFromText(text: string): SchedulePriority {
  const lower = text.toLocaleLowerCase();
  if (lower.includes("максим") || lower.includes("критич") || lower.includes("critical")) {
    return "critical";
  }
  if (lower.includes("сроч") || lower.includes("важн")) {
    return "high";
  }
  if (lower.includes("неваж") || lower.includes("низк")) {
    return "low";
  }
  return "medium";
}

function parseAutoplanTasksFromText(text: string, baseDate: string): ScheduleAutoTask[] {
  const lines = text.split(/\r?\n/);
  const tasks: ScheduleAutoTask[] = [];
  let category = "";

  for (const rawLine of lines) {
    const cleaned = rawLine.replace(/^[\s*•\-–—\d.)]+/, "").trim();
    if (!cleaned) {
      continue;
    }

    if (cleaned.endsWith(":") && cleaned.length <= 80) {
      category = cleaned.slice(0, -1).trim();
      continue;
    }

    const range = parseTimeRangeFromText(cleaned);
    const date = inferExplicitDateFromText(cleaned, baseDate);
    const durationMinutes =
      parseDurationFromText(cleaned) ??
      getDurationFromRange(range?.start, range?.end) ??
      inferDefaultTaskDuration(cleaned, category);
    const type: ScheduleEventType = date && range ? "fixed" : "flexible";

    tasks.push(
      normalizeScheduleAutoTask({
        id: createScheduleId("autotask"),
        title: inferAutoTaskTitle(cleaned),
        description: cleaned,
        category: category || inferAutoTaskCategory(cleaned),
        priority: inferPriorityFromText(cleaned),
        durationMinutes,
        frequency: inferAutoTaskFrequency(cleaned),
        date,
        start: range?.start,
        end: range?.end,
        deadline: inferDeadlineFromText(cleaned, baseDate),
        type,
        canMove: type !== "fixed",
        canSplit: type !== "fixed" && durationMinutes >= 50,
        sourceText: cleaned,
      })
    );
  }

  return tasks;
}

function inferExplicitDateFromText(text: string, baseDate: string): string | undefined {
  const isoMatch = text.match(/\b(\d{4}-\d{2}-\d{2})\b/);
  if (isoMatch) {
    return normalizeOptionalDate(isoMatch[1]);
  }
  return inferDateFromText(text, baseDate);
}

function inferAutoTaskTitle(text: string): string {
  const beforeColon = text.includes(":") ? text.split(":")[0] : text;
  const cleaned = beforeColon
    .replace(/\([^)]*\)/g, "")
    .replace(/\b\d{4}-\d{2}-\d{2}\b/g, "")
    .replace(/\d{1,2}(?::[0-5]\d)?\s*(?:[ap]\.?\s*m\.?)?/gi, "")
    .replace(/\s+/g, " ")
    .trim();
  return normalizeScheduleEventTitle(cleaned || text);
}

function inferAutoTaskCategory(text: string): string | undefined {
  const lower = text.toLocaleLowerCase();
  if (lower.includes("англий")) {
    return "Учёба";
  }
  if (lower.includes("работ") || lower.includes("монтаж")) {
    return "Обязанности";
  }
  if (lower.includes("друз") || lower.includes("пк") || lower.includes("игр")) {
    return "Развлечение";
  }
  if (lower.includes("зал") || lower.includes("вел") || lower.includes("помы")) {
    return "Жизненные нужды";
  }
  return undefined;
}

function inferAutoTaskFrequency(text: string): ScheduleAutoTaskFrequency {
  const lower = text.toLocaleLowerCase();
  if (lower.includes("каждый день") || lower.includes("ежеднев")) {
    return "daily";
  }
  if (
    lower.includes("не каждый день") ||
    lower.includes("иногда") ||
    lower.includes("через день") ||
    lower.includes("раз в неделю")
  ) {
    return "some-days";
  }
  return "once";
}

function inferDefaultTaskDuration(text: string, category: string): number {
  const lower = `${text} ${category}`.toLocaleLowerCase();
  if (lower.includes("помы")) {
    return 30;
  }
  if (lower.includes("зал")) {
    return 90;
  }
  if (lower.includes("вел")) {
    return 60;
  }
  if (lower.includes("работ") || lower.includes("монтаж")) {
    return 180;
  }
  if (lower.includes("англий")) {
    return 60;
  }
  if (lower.includes("рис") || lower.includes("худож")) {
    return 60;
  }
  if (lower.includes("друз") || lower.includes("гуля")) {
    return 120;
  }
  if (lower.includes("пк") || lower.includes("игр")) {
    return 60;
  }
  return 60;
}

function createAutoTasksFromTemplate(
  task: ScheduleTaskTemplate,
  startDate: string,
  horizonDays: number
): ScheduleAutoTask[] {
  const baseMinutes =
    task.goalMinutes ??
    task.durationMinutes ??
    (task.minDurationMinutes && task.maxDurationMinutes
      ? Math.round((task.minDurationMinutes + task.maxDurationMinutes) / 2)
      : undefined) ??
    (task.goalCount ? task.goalCount * 60 : 60);
  const periodMultiplier =
    task.goalPeriod === "day" ? horizonDays : Math.max(1, Math.ceil(horizonDays / 7));
  const totalMinutes = Math.max(
    MIN_EVENT_DURATION,
    Math.min(
      MAX_EVENT_DURATION * periodMultiplier,
      task.goalPeriod === "day" ? baseMinutes : baseMinutes * periodMultiplier
    )
  );
  const chunkDurations = getTemplateChunkDurations(
    task,
    totalMinutes,
    task.goalPeriod === "day" ? 1 : periodMultiplier
  );
  const frequency: ScheduleAutoTaskFrequency = task.goalPeriod === "day" ? "daily" : "once";

  return chunkDurations.map((durationMinutes, index) =>
    normalizeScheduleAutoTask({
      id: `${task.id}-autoplan-${index + 1}`,
      title:
        chunkDurations.length > 1
          ? `${task.title} ${index + 1}/${chunkDurations.length}`
          : task.title,
      description: task.details || task.description,
      category: task.category,
      priority: task.priority,
      durationMinutes,
      frequency,
      start: task.preferredTimeOfDay,
      type: task.type ?? "flexible",
      canMove: task.type !== "fixed",
      canSplit: false,
      sourceRoutineId: task.id,
    })
  );
}

function getTemplateChunkDurations(
  task: ScheduleTaskTemplate,
  totalMinutes: number,
  periodMultiplier: number
): number[] {
  if (task.canSplit === false) {
    return [totalMinutes];
  }

  const baseCount = task.goalCount
    ? Math.max(1, task.goalCount * periodMultiplier)
    : undefined;
  const defaults = getDefaultRoutineChunkRange(totalMinutes);
  const minChunk = Math.max(
    MIN_EVENT_DURATION,
    Math.min(
      totalMinutes,
      task.minDurationMinutes ?? defaults.minChunkMinutes
    )
  );
  const maxChunk = Math.max(
    minChunk,
    Math.min(
      totalMinutes,
      task.maxDurationMinutes ?? defaults.maxChunkMinutes
    )
  );
  const chunkCount =
    baseCount ??
    (totalMinutes <= 90
      ? 1
      : Math.max(1, Math.ceil(totalMinutes / maxChunk)));
  const durations: number[] = [];
  let remaining = totalMinutes;

  for (let index = 0; index < chunkCount; index += 1) {
    const slotsLeft = chunkCount - index;
    const duration =
      slotsLeft === 1
        ? remaining
        : Math.max(minChunk, Math.min(maxChunk, Math.round(remaining / slotsLeft)));
    durations.push(duration);
    remaining -= duration;
  }

  if (remaining > 0) {
    durations[durations.length - 1] += remaining;
  }

  return durations.filter((duration) => duration >= MIN_EVENT_DURATION);
}

function getDefaultRoutineChunkRange(totalMinutes: number): {
  minChunkMinutes: number;
  maxChunkMinutes: number;
} {
  if (totalMinutes <= 90) {
    return { minChunkMinutes: totalMinutes, maxChunkMinutes: totalMinutes };
  }
  if (totalMinutes <= 240) {
    return { minChunkMinutes: 60, maxChunkMinutes: 90 };
  }
  return { minChunkMinutes: 90, maxChunkMinutes: 120 };
}

function getTaskTargetMinutesForHorizon(
  task: ScheduleTaskTemplate,
  horizonDays: number
): number {
  const baseMinutes =
    task.goalMinutes ??
    task.durationMinutes ??
    (task.goalCount ? task.goalCount * 60 : 0);
  if (baseMinutes <= 0) {
    return 0;
  }
  return task.goalPeriod === "day"
    ? baseMinutes * horizonDays
    : baseMinutes * Math.max(1, Math.ceil(horizonDays / 7));
}

function buildTaskCoverage(
  taskBase: ScheduleTaskTemplate[],
  changes: SchedulePreviewChange[],
  horizonDays: number
): ScheduleAutoplanTaskCoverage[] {
  return taskBase.map((task) => {
    const addedEvents = changes
      .filter((change): change is Extract<SchedulePreviewChange, { kind: "add" }> =>
        change.kind === "add"
      )
      .map((change) => change.event)
      .filter((event) => event.taskId === task.id || event.generatedFromTaskId === task.id);
    const plannedMinutes = addedEvents.reduce(
      (sum, event) => sum + getEventDurationMinutes(event),
      0
    );

    return {
      taskId: task.id,
      title: task.title,
      targetMinutes: getTaskTargetMinutesForHorizon(task, horizonDays),
      plannedMinutes,
      plannedCount: addedEvents.length,
    };
  });
}

function expandAutoTaskInstances(
  tasks: ScheduleAutoTask[],
  startDate: string,
  horizonDays: number
): Array<{ task: ScheduleAutoTask; date: string; index: number }> {
  const instances: Array<{ task: ScheduleAutoTask; date: string; index: number }> = [];
  tasks.forEach((task, taskIndex) => {
    if (task.date) {
      instances.push({ task, date: task.date, index: taskIndex });
      return;
    }

    if (task.frequency === "daily") {
      for (let index = 0; index < horizonDays; index += 1) {
        instances.push({ task, date: addScheduleDays(startDate, index), index: taskIndex });
      }
      return;
    }

    if (task.frequency === "some-days") {
      for (let index = 0; index < horizonDays; index += 2) {
        instances.push({ task, date: addScheduleDays(startDate, index), index: taskIndex });
      }
      return;
    }

    instances.push({ task, date: startDate, index: taskIndex });
  });
  return instances;
}

function compareAutoTaskInstances(
  left: { task: ScheduleAutoTask; date: string; index: number },
  right: { task: ScheduleAutoTask; date: string; index: number }
): number {
  const priorityDiff =
    schedulePriorityWeight(right.task.priority) - schedulePriorityWeight(left.task.priority);
  if (priorityDiff !== 0) {
    return priorityDiff;
  }
  if (left.date !== right.date) {
    return left.date.localeCompare(right.date);
  }
  return left.index - right.index;
}

function schedulePriorityWeight(priority: SchedulePriority | undefined): number {
  if (priority === "critical") {
    return 4;
  }
  if (priority === "high") {
    return 3;
  }
  if (priority === "medium" || !priority) {
    return 2;
  }
  return 1;
}

function createEventFromAutoTask(
  task: ScheduleAutoTask,
  date: string,
  overrides: Partial<ScheduleEvent> = {}
): ScheduleEvent {
  const start = overrides.start ?? task.start;
  const durationMinutes = normalizeScheduleDuration(
    overrides.durationMinutes ?? task.durationMinutes,
    getDurationFromRange(start, overrides.end ?? task.end) ?? 60
  );
  const startDate = normalizeScheduleDate(overrides.date ?? task.date ?? date);
  const startTime = start ?? DEFAULT_DAY_START;
  const startAbs = dateTimeToAbsoluteMinute(startDate, startTime);
  const endPoint = absoluteMinuteToDateTime(startAbs + durationMinutes);

  return normalizeScheduleEvent({
    id: overrides.id ?? createScheduleId("event"),
    taskId: overrides.taskId ?? task.sourceRoutineId,
    title: overrides.title ?? task.title,
    description: overrides.description ?? task.description,
    date: startDate,
    start: startTime,
    end: overrides.end ?? endPoint.time,
    endDate: overrides.endDate ?? (endPoint.date !== startDate ? endPoint.date : undefined),
    durationMinutes,
    type: overrides.type ?? task.type ?? "flexible",
    category: overrides.category ?? task.category,
    priority: overrides.priority ?? task.priority ?? "medium",
    status: overrides.status ?? "planned",
    canMove: overrides.canMove ?? task.canMove ?? true,
    canSplit: overrides.canSplit ?? task.canSplit ?? false,
    deadline: overrides.deadline ?? task.deadline,
    generatedFromTaskId: task.sourceRoutineId ?? task.id,
    generatedFromRoutineId: task.sourceRoutineId,
    autoGenerated: true,
  });
}

function placeAutoTaskInstance(
  payload: SchedulePayload,
  task: ScheduleAutoTask,
  startDate: string,
  horizonEndDate: string
): ScheduleEvent[] {
  const durationMinutes = normalizeScheduleDuration(task.durationMinutes, 60);
  const endDate = task.deadline && task.deadline < horizonEndDate ? task.deadline : horizonEndDate;
  const suggestions = buildScheduleSuggestions(
    payload,
    {
      title: task.title,
      description: task.description,
      durationMinutes,
      dateRangeStart: startDate,
      dateRangeEnd: endDate,
      preferredTime: task.start,
      deadline: task.deadline,
      priority: task.priority,
      category: task.category,
      canMove: true,
      canSplit: task.canSplit,
      type: task.type ?? "flexible",
    },
    startDate
  );

  if (suggestions[0]) {
    return [
      normalizeScheduleEvent({
        ...suggestions[0].event,
        taskId: task.sourceRoutineId,
        generatedFromTaskId: task.sourceRoutineId ?? task.id,
        generatedFromRoutineId: task.sourceRoutineId,
        autoGenerated: true,
      }),
    ];
  }

  if (!task.canSplit || durationMinutes < MIN_SPLIT_CHUNK_MINUTES * 2) {
    return [];
  }

  const placed: ScheduleEvent[] = [];
  let remaining = durationMinutes;
  let workingPayload = payload;
  while (remaining >= MIN_SPLIT_CHUNK_MINUTES) {
    const chunkDuration = Math.min(
      remaining,
      Math.max(MIN_SPLIT_CHUNK_MINUTES, Math.ceil(durationMinutes / 2))
    );
    const chunkSuggestions = buildScheduleSuggestions(
      workingPayload,
      {
        title: task.title,
        description: task.description,
        durationMinutes: chunkDuration,
        dateRangeStart: startDate,
        dateRangeEnd: endDate,
        preferredTime: task.start,
        deadline: task.deadline,
        priority: task.priority,
        category: task.category,
        canMove: true,
        canSplit: false,
        type: task.type ?? "flexible",
      },
      startDate
    );
    const suggestion = chunkSuggestions[0];
    if (!suggestion) {
      break;
    }
    const event = normalizeScheduleEvent({
      ...suggestion.event,
      title: `${task.title} (${placed.length + 1})`,
      taskId: task.sourceRoutineId,
      generatedFromTaskId: task.sourceRoutineId ?? task.id,
      generatedFromRoutineId: task.sourceRoutineId,
      autoGenerated: true,
    });
    placed.push(event);
    workingPayload = {
      ...workingPayload,
      events: normalizeScheduleEvents([...workingPayload.events, event]),
    };
    remaining -= chunkDuration;
  }

  return remaining <= 0 ? placed : [];
}

function isAutoGeneratedEventInDateRange(
  event: ScheduleEvent,
  startDate: string,
  endDate: string
): boolean {
  if (!event.autoGenerated) {
    return false;
  }
  const startAbs = getDateDayIndex(startDate) * DAY_MINUTES;
  const endAbs = (getDateDayIndex(endDate) + 1) * DAY_MINUTES;
  const eventInterval = getEventInterval(event);
  return eventInterval.end > startAbs && eventInterval.start < endAbs;
}

function normalizeAssistantTitle(value: string): string {
  const cleaned = value
    .replace(/мне нужно/gi, "")
    .replace(/надо/gi, "")
    .replace(/примерно/gi, "")
    .replace(
      /\d+(?:[,.]\d+)?\s*(?:часов|часа|час|ч|минут|минуты|мин|м|hours?|minutes?|m|h)(?=$|\s|[.,;:!?])/gi,
      ""
    )
    .replace(/\s+/g, " ")
    .trim();
  return normalizeScheduleEventTitle(cleaned || value || "Новое дело");
}

function buildSuggestionReason(options: {
  preferred: boolean;
  lowLoad: boolean;
  deadline: boolean;
}): string {
  const reasons: string[] = [];
  if (options.preferred) {
    reasons.push("попадает в предпочтительное время");
  }
  if (options.lowLoad) {
    reasons.push("день не перегружен");
  }
  if (options.deadline) {
    reasons.push("успевает до дедлайна");
  }
  return reasons.length > 0 ? reasons.join(", ") : "свободное окно без пересечений";
}

function normalizeComparable(value: string): string {
  return value.trim().toLocaleLowerCase();
}

function normalizeGoalCategoryKey(goal: ScheduleGoal): string {
  return normalizeComparable(goal.category || goal.title);
}
